package event

import (
	"context"
	"errors"
	"time"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
	"github.com/biairmal/guest-management-be/internal/features/events/workflowstep"
	"github.com/biairmal/guest-management-be/internal/features/events/workflowsteptemplate"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../../mocks/events/event/mock_service.go -package=mockevent github.com/biairmal/guest-management-be/internal/features/events/event Service

// Service defines the application-level operations for events.
type Service interface {
	Create(ctx context.Context, in CreateEventInput) (*Event, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Event, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateEventInput) (*Event, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Event], error)
}

// eventServiceImpl is the concrete implementation of Service.
type eventServiceImpl struct {
	repo             repository.Repository[Event, uuid.UUID]
	templateRepo     repository.Repository[workflowsteptemplate.WorkflowStepTemplate, uuid.UUID]
	workflowStepRepo repository.Repository[workflowstep.WorkflowStep, uuid.UUID]
	logger           logger.Logger
}

// NewService returns an Service with the given dependencies.
// templateRepo/workflowStepRepo back Create's default-workflow-step copy
// (see copyWorkflowStepTemplates).
func NewService(
	logger logger.Logger,
	repo repository.Repository[Event, uuid.UUID],
	templateRepo repository.Repository[workflowsteptemplate.WorkflowStepTemplate, uuid.UUID],
	workflowStepRepo repository.Repository[workflowstep.WorkflowStep, uuid.UUID],
) Service {
	return &eventServiceImpl{logger: logger, repo: repo, templateRepo: templateRepo, workflowStepRepo: workflowStepRepo}
}

// Create creates a new event. ID is generated by the service; is_multi_day
// is derived from start_date/end_date, not caller-supplied. Audit fields
// (created_at, updated_at) are set by the AuditableRepository.
//
//nolint:gocritic // DTO passed by value to match the by-value CreateInput convention across feature services
func (s *eventServiceImpl) Create(ctx context.Context, in CreateEventInput) (*Event, error) {
	if in.EndDate.Before(in.StartDate) {
		return nil, errorz.BadRequest().WithMessage("end_date must not be before start_date")
	}

	entity := &Event{
		ID:          uuid.New(),
		TenantID:    in.TenantID,
		CategoryID:  in.CategoryID,
		Name:        in.Name,
		Description: in.Description,
		StartDate:   in.StartDate,
		EndDate:     in.EndDate,
		IsMultiDay:  isMultiDay(in.StartDate, in.EndDate),
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("event already exists")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid event data")
		}
		s.logger.ErrorWithContext(ctx, "event create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create event")
	}

	s.copyWorkflowStepTemplates(ctx, entity)

	s.logger.InfoWithContext(ctx, "event created", logger.F("id", entity.ID))
	return entity, nil
}

// copyWorkflowStepTemplates seeds entity's workflow steps from its
// category's workflow_step_templates, if any exist — the customizable
// starting point a UI shows right after creating an event. This is
// best-effort: templates are an optional default (a category may have
// none), so a lookup or copy failure is logged but does not fail event
// creation; the caller can always fix up steps afterward via
// WorkflowStepService.Sync.
func (s *eventServiceImpl) copyWorkflowStepTemplates(ctx context.Context, event *Event) {
	templates, _, err := s.templateRepo.List(ctx, &repository.ListOptions{
		Filter: repository.Filter{Conditions: []repository.FilterCondition{
			{Field: "category_id", Operator: repository.FilterOperatorEq, Value: event.CategoryID},
		}},
		Pagination: repository.Pagination{Limit: query.DefaultMaxSize},
		Sorts:      []repository.Sort{{Field: "order_index", Direction: repository.SortAsc}},
	})
	if err != nil {
		s.logger.ErrorWithContext(ctx, "workflow step template lookup failed",
			logger.F("event_id", event.ID), logger.F("category_id", event.CategoryID), logger.F("error", err))
		return
	}

	for _, tmpl := range templates {
		step := &workflowstep.WorkflowStep{
			ID:             uuid.New(),
			EventID:        event.ID,
			Name:           tmpl.Name,
			OrderIndex:     tmpl.OrderIndex,
			AllowsMultiple: tmpl.AllowsMultiple,
		}
		if err := s.workflowStepRepo.Create(ctx, step); err != nil {
			s.logger.ErrorWithContext(ctx, "workflow step template copy failed",
				logger.F("event_id", event.ID), logger.F("template_id", tmpl.ID), logger.F("error", err))
		}
	}
}

// GetByID returns an event by ID, or errorz.NotFound if not found or soft-deleted.
func (s *eventServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*Event, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event")
	}
	return entity, nil
}

// Update updates an event. Only non-nil fields in UpdateEventInput are
// applied; is_multi_day is re-derived whenever either date changes. The
// updated_at field is set by the AuditableRepository.
func (s *eventServiceImpl) Update(ctx context.Context, id uuid.UUID, in UpdateEventInput) (*Event, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event")
	}

	if in.CategoryID != nil {
		entity.CategoryID = *in.CategoryID
	}
	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.Description != nil {
		entity.Description = in.Description
	}
	if in.StartDate != nil {
		entity.StartDate = *in.StartDate
	}
	if in.EndDate != nil {
		entity.EndDate = *in.EndDate
	}
	if entity.EndDate.Before(entity.StartDate) {
		return nil, errorz.BadRequest().WithMessage("end_date must not be before start_date")
	}
	entity.IsMultiDay = isMultiDay(entity.StartDate, entity.EndDate)

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update event")
	}

	s.logger.InfoWithContext(ctx, "event updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes an event. The AuditableRepository handles setting
// deleted_at and updated_at.
func (s *eventServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete event")
	}
	s.logger.InfoWithContext(ctx, "event deleted", logger.F("id", id))
	return nil
}

// EventListConfig declares the allow-listed sort/filter fields for event
// list queries, enforced here in the service via query.ValidateListParams
// and reused by Handler.List for query.ParseListParams.
var EventListConfig = query.ListParseConfig{
	AllowedSortFields: []string{
		"id", "tenant_id", "category_id", "name", "start_date", "end_date", "is_multi_day", "created_at", "updated_at",
	},
	AllowedFilterFields: []string{"tenant_id", "category_id", "name"},
}

// List returns events with filter, sort, and pagination from query.ListParams.
func (s *eventServiceImpl) List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Event], error) {
	if err := query.ValidateListParams(params, EventListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	items, total, err := s.repo.List(ctx, query.ToListOptions(params))
	if err != nil {
		s.logger.ErrorWithContext(ctx, "event list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list events")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// isMultiDay reports whether start and end fall on different calendar days,
// each evaluated in its own time.Time location.
func isMultiDay(start, end time.Time) bool {
	sy, sm, sd := start.Date()
	ey, em, ed := end.Date()
	return sy != ey || sm != em || sd != ed
}
