package event

import (
	"context"
	"errors"
	"time"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/biairmal/go-sdk/lib/sqlkit"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
	"github.com/biairmal/guest-management-be/internal/features/events/workflowstep"
	"github.com/biairmal/guest-management-be/internal/features/events/workflowsteptemplate"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../../mocks/events/event/mock_service.go -package=mockevent github.com/biairmal/guest-management-be/internal/features/events/event Service

// Service defines the application-level operations for events.
type Service interface {
	Create(ctx context.Context, in CreateEventInput) (*Event, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Event, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateEventInput) (*Event, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Event], error)
}

// eventServiceImpl is the concrete implementation of Service.
type eventServiceImpl struct {
	repo             repository.Repository[Event, uuid.UUID]
	templateRepo     repository.Repository[workflowsteptemplate.WorkflowStepTemplate, uuid.UUID]
	workflowStepRepo repository.Repository[workflowstep.WorkflowStep, uuid.UUID]
	ticketTypeSeeder TicketTypeSeeder
	db               *sqlkit.DB
	logger           logger.Logger
}

// NewService returns an Service with the given dependencies.
// templateRepo/workflowStepRepo back Create's default-workflow-step copy
// (see copyWorkflowStepTemplates); ticketTypeSeeder backs Create's
// default-ticket-type copy (B12). db backs Create's transactional wrap of
// both copies (go-sdk's (*sqlkit.DB).WithTransaction), following
// NewUserService's precedent (db last).
func NewService(
	logger logger.Logger,
	repo repository.Repository[Event, uuid.UUID],
	templateRepo repository.Repository[workflowsteptemplate.WorkflowStepTemplate, uuid.UUID],
	workflowStepRepo repository.Repository[workflowstep.WorkflowStep, uuid.UUID],
	ticketTypeSeeder TicketTypeSeeder,
	db *sqlkit.DB,
) Service {
	return &eventServiceImpl{
		logger: logger, repo: repo, templateRepo: templateRepo, workflowStepRepo: workflowStepRepo,
		ticketTypeSeeder: ticketTypeSeeder, db: db,
	}
}

// Create creates a new event. ID is generated by the service; is_multi_day
// is derived from start_date/end_date, not caller-supplied. Audit fields
// (created_at, updated_at) are set by the AuditableRepository.
//
// The event insert, the workflow-step-template copy, and the
// ticket-type-template seed (B12) all run inside a single transaction
// (go-sdk's (*sqlkit.DB).WithTransaction, the same mechanism users'
// TransferMaster uses): a failure in any of the three rolls back the whole
// event creation instead of committing a partially-seeded event.
//
//nolint:gocritic // DTO passed by value to match the by-value CreateInput convention across feature services
func (s *eventServiceImpl) Create(ctx context.Context, in CreateEventInput) (*Event, error) {
	if in.EndDate.Before(in.StartDate) {
		return nil, errorz.BadRequest().WithMessage("end_date must not be before start_date")
	}

	entity := buildEvent(in)

	err := s.db.WithTransaction(ctx, func(txCtx context.Context) error {
		return s.createEvent(txCtx, entity)
	})
	if err != nil {
		return nil, err
	}

	s.logger.InfoWithContext(ctx, "event created", logger.F("id", entity.ID))
	return entity, nil
}

// buildEvent constructs a new Event from in: ID is generated, is_multi_day
// is derived from start_date/end_date, and rsvp_required defaults to true
// when omitted. Pure aside from uuid.New(), so it's unit-tested directly
// without a service/repo/db.
//
//nolint:gocritic // DTO passed by value to match the by-value CreateInput convention across feature services
func buildEvent(in CreateEventInput) *Event {
	rsvpRequired := true
	if in.RsvpRequired != nil {
		rsvpRequired = *in.RsvpRequired
	}

	return &Event{
		ID:           uuid.New(),
		TenantID:     in.TenantID,
		CategoryID:   in.CategoryID,
		Name:         in.Name,
		Description:  in.Description,
		StartDate:    in.StartDate,
		EndDate:      in.EndDate,
		IsMultiDay:   isMultiDay(in.StartDate, in.EndDate),
		RsvpRequired: rsvpRequired,
	}
}

// createEvent inserts entity, then copies its category's
// workflow-step-templates and ticket-type-templates onto it, all against
// ctx — the transaction-carrying context Create's WithTransaction call
// supplies, so a failure in any step rolls back the others. Split out from
// Create purely for testability: it can be exercised directly against
// mocked collaborators without a live database/transaction (see
// docs/TESTING.md "Unit vs integration"), mirroring users' transferMaster.
func (s *eventServiceImpl) createEvent(ctx context.Context, entity *Event) error {
	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return errorz.Conflict().WithMessage("event already exists")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return errorz.UnprocessableEntity().WithMessage("invalid event data")
		}
		s.logger.ErrorWithContext(ctx, "event create failed", logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create event")
	}

	if err := s.copyWorkflowStepTemplates(ctx, entity); err != nil {
		return err
	}
	return s.ticketTypeSeeder.SeedFromCategoryTemplates(ctx, entity.ID, entity.CategoryID)
}

// copyWorkflowStepTemplates seeds entity's workflow steps from its
// category's workflow_step_templates, if any exist — the customizable
// starting point a UI shows right after creating an event. Runs inside
// Create's transaction: a lookup or per-template copy failure now aborts
// event creation (returning an errorz-wrapped error) instead of being
// logged and skipped — a partial copy silently committed by a
// no-longer-best-effort wrapper would be a worse, silently-inconsistent
// outcome than the request failing outright so the caller can retry.
func (s *eventServiceImpl) copyWorkflowStepTemplates(ctx context.Context, event *Event) error {
	templates, _, err := s.templateRepo.List(ctx, &repository.ListOptions{
		Filter: repository.Filter{Conditions: []repository.FilterCondition{
			{Field: "category_id", Operator: repository.FilterOperatorEq, Value: event.CategoryID},
		}},
		Pagination: repository.Pagination{Limit: query.DefaultMaxSize},
		Sorts:      []repository.Sort{{Field: "order_index", Direction: repository.SortAsc}},
	})
	if err != nil {
		s.logger.ErrorWithContext(ctx, "workflow step template lookup failed",
			logger.F("event_id", event.ID), logger.F("category_id", event.CategoryID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to look up workflow step templates")
	}

	for _, tmpl := range templates {
		step := &workflowstep.WorkflowStep{
			ID:             uuid.New(),
			EventID:        event.ID,
			Name:           tmpl.Name,
			OrderIndex:     tmpl.OrderIndex,
			AllowsMultiple: tmpl.AllowsMultiple,
		}
		if err := s.workflowStepRepo.Create(ctx, step); err != nil {
			s.logger.ErrorWithContext(ctx, "workflow step template copy failed",
				logger.F("event_id", event.ID), logger.F("template_id", tmpl.ID), logger.F("error", err))
			return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to copy workflow step template")
		}
	}
	return nil
}

// GetByID returns an event by ID, or errorz.NotFound if not found or soft-deleted.
func (s *eventServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*Event, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event")
	}
	return entity, nil
}

// Update updates an event. Only non-nil fields in UpdateEventInput are
// applied; is_multi_day is re-derived whenever either date changes. The
// updated_at field is set by the AuditableRepository.
func (s *eventServiceImpl) Update(ctx context.Context, id uuid.UUID, in UpdateEventInput) (*Event, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event")
	}

	if in.CategoryID != nil {
		entity.CategoryID = *in.CategoryID
	}
	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.Description != nil {
		entity.Description = in.Description
	}
	if in.StartDate != nil {
		entity.StartDate = *in.StartDate
	}
	if in.EndDate != nil {
		entity.EndDate = *in.EndDate
	}
	if in.RsvpRequired != nil {
		entity.RsvpRequired = *in.RsvpRequired
	}
	if entity.EndDate.Before(entity.StartDate) {
		return nil, errorz.BadRequest().WithMessage("end_date must not be before start_date")
	}
	entity.IsMultiDay = isMultiDay(entity.StartDate, entity.EndDate)

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update event")
	}

	s.logger.InfoWithContext(ctx, "event updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes an event. The AuditableRepository handles setting
// deleted_at and updated_at.
func (s *eventServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("event not found")
		}
		s.logger.ErrorWithContext(ctx, "event delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete event")
	}
	s.logger.InfoWithContext(ctx, "event deleted", logger.F("id", id))
	return nil
}

// EventListConfig declares the allow-listed sort/filter fields for event
// list queries, enforced here in the service via query.ValidateListParams
// and reused by Handler.List for query.ParseListParams.
var EventListConfig = query.ListParseConfig{
	AllowedSortFields: []string{
		"id", "tenant_id", "category_id", "name", "start_date", "end_date", "is_multi_day", "created_at", "updated_at",
	},
	AllowedFilterFields: []string{"tenant_id", "category_id", "name"},
}

// List returns events with filter, sort, and pagination from query.ListParams.
func (s *eventServiceImpl) List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Event], error) {
	if err := query.ValidateListParams(params, EventListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	items, total, err := s.repo.List(ctx, query.ToListOptions(params))
	if err != nil {
		s.logger.ErrorWithContext(ctx, "event list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list events")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// isMultiDay reports whether start and end fall on different calendar days,
// each evaluated in its own time.Time location.
func isMultiDay(start, end time.Time) bool {
	sy, sm, sd := start.Date()
	ey, em, ed := end.Date()
	return sy != ey || sm != em || sd != ed
}
