// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/templates (interfaces: MessageTemplateService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/templates/mock_service.go -package=mocktemplates github.com/biairmal/guest-management-be/internal/features/templates MessageTemplateService
//

// Package mocktemplates is a generated GoMock package.
package mocktemplates

import (
	context "context"
	reflect "reflect"

	dto "github.com/biairmal/go-sdk/lib/common/dto"
	query "github.com/biairmal/guest-management-be/internal/core/query"
	templates "github.com/biairmal/guest-management-be/internal/features/templates"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageTemplateService is a mock of MessageTemplateService interface.
type MockMessageTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageTemplateServiceMockRecorder
	isgomock struct{}
}

// MockMessageTemplateServiceMockRecorder is the mock recorder for MockMessageTemplateService.
type MockMessageTemplateServiceMockRecorder struct {
	mock *MockMessageTemplateService
}

// NewMockMessageTemplateService creates a new mock instance.
func NewMockMessageTemplateService(ctrl *gomock.Controller) *MockMessageTemplateService {
	mock := &MockMessageTemplateService{ctrl: ctrl}
	mock.recorder = &MockMessageTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageTemplateService) EXPECT() *MockMessageTemplateServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageTemplateService) Create(ctx context.Context, in templates.CreateInput) (*templates.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*templates.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageTemplateServiceMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageTemplateService)(nil).Create), ctx, in)
}

// Delete mocks base method.
func (m *MockMessageTemplateService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageTemplateServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageTemplateService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMessageTemplateService) GetByID(ctx context.Context, id uuid.UUID) (*templates.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*templates.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMessageTemplateServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMessageTemplateService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockMessageTemplateService) List(ctx context.Context, params *query.ListParams) (*dto.PageResponse[templates.MessageTemplate], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(*dto.PageResponse[templates.MessageTemplate])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessageTemplateServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageTemplateService)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockMessageTemplateService) Update(ctx context.Context, id uuid.UUID, in templates.UpdateInput) (*templates.MessageTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, in)
	ret0, _ := ret[0].(*templates.MessageTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMessageTemplateServiceMockRecorder) Update(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageTemplateService)(nil).Update), ctx, id, in)
}
