// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/staffing (interfaces: StaffAssignmentService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/staffing/mock_service.go -package=mockstaffing github.com/biairmal/guest-management-be/internal/features/staffing StaffAssignmentService
//

// Package mockstaffing is a generated GoMock package.
package mockstaffing

import (
	context "context"
	reflect "reflect"

	dto "github.com/biairmal/go-sdk/lib/common/dto"
	query "github.com/biairmal/guest-management-be/internal/core/query"
	staffing "github.com/biairmal/guest-management-be/internal/features/staffing"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStaffAssignmentService is a mock of StaffAssignmentService interface.
type MockStaffAssignmentService struct {
	ctrl     *gomock.Controller
	recorder *MockStaffAssignmentServiceMockRecorder
	isgomock struct{}
}

// MockStaffAssignmentServiceMockRecorder is the mock recorder for MockStaffAssignmentService.
type MockStaffAssignmentServiceMockRecorder struct {
	mock *MockStaffAssignmentService
}

// NewMockStaffAssignmentService creates a new mock instance.
func NewMockStaffAssignmentService(ctrl *gomock.Controller) *MockStaffAssignmentService {
	mock := &MockStaffAssignmentService{ctrl: ctrl}
	mock.recorder = &MockStaffAssignmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffAssignmentService) EXPECT() *MockStaffAssignmentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStaffAssignmentService) Create(ctx context.Context, eventID uuid.UUID, in staffing.CreateAssignmentInput) (*staffing.EventStaffAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, in)
	ret0, _ := ret[0].(*staffing.EventStaffAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStaffAssignmentServiceMockRecorder) Create(ctx, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStaffAssignmentService)(nil).Create), ctx, eventID, in)
}

// Delete mocks base method.
func (m *MockStaffAssignmentService) Delete(ctx context.Context, eventID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStaffAssignmentServiceMockRecorder) Delete(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStaffAssignmentService)(nil).Delete), ctx, eventID, id)
}

// GetByID mocks base method.
func (m *MockStaffAssignmentService) GetByID(ctx context.Context, eventID, id uuid.UUID) (*staffing.EventStaffAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, eventID, id)
	ret0, _ := ret[0].(*staffing.EventStaffAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStaffAssignmentServiceMockRecorder) GetByID(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStaffAssignmentService)(nil).GetByID), ctx, eventID, id)
}

// List mocks base method.
func (m *MockStaffAssignmentService) List(ctx context.Context, eventID uuid.UUID, params *query.ListParams) (*dto.PageResponse[staffing.EventStaffAssignment], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, params)
	ret0, _ := ret[0].(*dto.PageResponse[staffing.EventStaffAssignment])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStaffAssignmentServiceMockRecorder) List(ctx, eventID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStaffAssignmentService)(nil).List), ctx, eventID, params)
}

// Update mocks base method.
func (m *MockStaffAssignmentService) Update(ctx context.Context, eventID, id uuid.UUID, in staffing.UpdateAssignmentInput) (*staffing.EventStaffAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, eventID, id, in)
	ret0, _ := ret[0].(*staffing.EventStaffAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStaffAssignmentServiceMockRecorder) Update(ctx, eventID, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStaffAssignmentService)(nil).Update), ctx, eventID, id, in)
}
