# golangci-lint configuration (guest-management-be)
# See https://golangci-lint.run/usage/configuration/ and
# https://golangci-lint.run/docs/configuration/file/

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  noctx:
    check-exported: false

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofumpt
    - goimports
    - typecheck
    - gocritic
    - gocyclo
    - unconvert
    - unparam
    - misspell
    - copyloopvar
    - revive
    - errname
    - errorlint
    - gosec
    - predeclared
    - gocognit
    - dupl
    - funlen
    - lll
    - nakedret
    - noctx
    - nolintlint

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-dirs:
    - vendor
    - bin
    - .git
    - out
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocognit
        - gocyclo
    - path: cmd/
      linters:
        - errcheck
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    - text: "exported function.*should have comment"
      linters:
        - revive
    - text: "package comment should be of the form"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
