// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/roles (interfaces: RolePermissionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/roles/mock_role_permission_repository.go -package=mockroles github.com/biairmal/guest-management-be/internal/features/roles RolePermissionRepository
//

// Package mockroles is a generated GoMock package.
package mockroles

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRolePermissionRepository is a mock of RolePermissionRepository interface.
type MockRolePermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRolePermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockRolePermissionRepositoryMockRecorder is the mock recorder for MockRolePermissionRepository.
type MockRolePermissionRepositoryMockRecorder struct {
	mock *MockRolePermissionRepository
}

// NewMockRolePermissionRepository creates a new mock instance.
func NewMockRolePermissionRepository(ctrl *gomock.Controller) *MockRolePermissionRepository {
	mock := &MockRolePermissionRepository{ctrl: ctrl}
	mock.recorder = &MockRolePermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePermissionRepository) EXPECT() *MockRolePermissionRepositoryMockRecorder {
	return m.recorder
}

// PermissionCodesByRoleID mocks base method.
func (m *MockRolePermissionRepository) PermissionCodesByRoleID(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionCodesByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermissionCodesByRoleID indicates an expected call of PermissionCodesByRoleID.
func (mr *MockRolePermissionRepositoryMockRecorder) PermissionCodesByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionCodesByRoleID", reflect.TypeOf((*MockRolePermissionRepository)(nil).PermissionCodesByRoleID), ctx, roleID)
}
