package tickettypetemplate

import (
	"context"
	"encoding/json"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
)

// emptyJSONObject is the default value stored for rules when the caller
// omits it, matching the ticket_type_templates.rules column default of '{}'.
var emptyJSONObject = json.RawMessage("{}")

// TicketTypeTemplateListConfig declares the allow-listed sort/filter fields
// for ticket type template list queries, enforced here in the service via
// query.ValidateListParams and reused by Handler.List for
// query.ParseListParams. category_id is always scoped from the URL, not a
// query filter.
var TicketTypeTemplateListConfig = query.ListParseConfig{
	AllowedSortFields:   []string{"id", "name", "created_at", "updated_at"},
	AllowedFilterFields: []string{"name"},
}

// Service defines the application-level operations for category-scoped
// ticket type templates. Every operation takes the owning category's ID so a
// template can never be read, changed, or deleted through a mismatched
// category in the URL.
type Service interface {
	Create(
		ctx context.Context, categoryID uuid.UUID, in CreateTicketTypeTemplateInput,
	) (*TicketTypeTemplate, error)
	GetByID(ctx context.Context, categoryID, id uuid.UUID) (*TicketTypeTemplate, error)
	Update(
		ctx context.Context, categoryID, id uuid.UUID, in UpdateTicketTypeTemplateInput,
	) (*TicketTypeTemplate, error)
	Delete(ctx context.Context, categoryID, id uuid.UUID) error
	List(
		ctx context.Context, categoryID uuid.UUID, params *query.ListParams,
	) (*common.PageResponse[TicketTypeTemplate], error)
}

// ticketTypeTemplateServiceImpl is the concrete implementation of Service.
type ticketTypeTemplateServiceImpl struct {
	repo   repository.Repository[TicketTypeTemplate, uuid.UUID]
	logger logger.Logger
}

// NewService returns a Service with the given dependencies.
func NewService(logger logger.Logger, repo repository.Repository[TicketTypeTemplate, uuid.UUID]) Service {
	return &ticketTypeTemplateServiceImpl{logger: logger, repo: repo}
}

// Create creates a new ticket type template under categoryID. ID is
// generated by the service; rules defaults to an empty JSON object when
// omitted. Audit fields (created_at, updated_at) are set by the
// AuditableRepository; the (category_id, name) uniqueness invariant is
// DB-enforced and surfaces as errorz.Conflict.
func (s *ticketTypeTemplateServiceImpl) Create(
	ctx context.Context, categoryID uuid.UUID, in CreateTicketTypeTemplateInput,
) (*TicketTypeTemplate, error) {
	rules := in.Rules
	if len(rules) == 0 {
		rules = emptyJSONObject
	}

	entity := &TicketTypeTemplate{ID: uuid.New(), CategoryID: categoryID, Name: in.Name, Rules: rules}
	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("ticket type template already exists for this category")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid ticket type template data")
		}
		s.logger.ErrorWithContext(ctx, "ticket type template create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create ticket type template")
	}

	s.logger.InfoWithContext(ctx, "ticket type template created",
		logger.F("id", entity.ID), logger.F("category_id", categoryID))
	return entity, nil
}

// GetByID returns a ticket type template by ID scoped to categoryID.
// Returns errorz.NotFound if the template doesn't exist, is soft-deleted, or
// belongs to a different category.
func (s *ticketTypeTemplateServiceImpl) GetByID(
	ctx context.Context, categoryID, id uuid.UUID,
) (*TicketTypeTemplate, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("ticket type template not found")
		}
		s.logger.ErrorWithContext(ctx, "ticket type template get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get ticket type template")
	}
	if entity.CategoryID != categoryID {
		return nil, errorz.NotFound().WithMessage("ticket type template not found")
	}
	return entity, nil
}

// Update updates a ticket type template scoped to categoryID. Only
// non-nil/non-empty fields in UpdateTicketTypeTemplateInput are applied. The
// updated_at field is set by the AuditableRepository; the
// (category_id, name) uniqueness invariant is DB-enforced and surfaces as
// errorz.Conflict.
func (s *ticketTypeTemplateServiceImpl) Update(
	ctx context.Context, categoryID, id uuid.UUID, in UpdateTicketTypeTemplateInput,
) (*TicketTypeTemplate, error) {
	entity, err := s.GetByID(ctx, categoryID, id)
	if err != nil {
		return nil, err
	}

	if in.Name != nil {
		entity.Name = *in.Name
	}
	if len(in.Rules) > 0 {
		entity.Rules = in.Rules
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("ticket type template not found")
		}
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("ticket type template already exists for this category")
		}
		s.logger.ErrorWithContext(ctx, "ticket type template update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update ticket type template")
	}

	s.logger.InfoWithContext(ctx, "ticket type template updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a ticket type template scoped to categoryID. The
// AuditableRepository handles setting deleted_at and updated_at. Deleting a
// template never retroactively changes ticket types already seeded from it
// (B12 AC6) — there is no FK from ticket_types back to this table.
func (s *ticketTypeTemplateServiceImpl) Delete(ctx context.Context, categoryID, id uuid.UUID) error {
	if _, err := s.GetByID(ctx, categoryID, id); err != nil {
		return err
	}
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("ticket type template not found")
		}
		s.logger.ErrorWithContext(ctx, "ticket type template delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete ticket type template")
	}
	s.logger.InfoWithContext(ctx, "ticket type template deleted", logger.F("id", id))
	return nil
}

// List returns the ticket type templates for categoryID with filter, sort,
// and pagination from query.ListParams. The category_id scope is enforced
// server-side regardless of query filters.
func (s *ticketTypeTemplateServiceImpl) List(
	ctx context.Context, categoryID uuid.UUID, params *query.ListParams,
) (*common.PageResponse[TicketTypeTemplate], error) {
	if err := query.ValidateListParams(params, TicketTypeTemplateListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	opts := query.ToListOptions(params)
	opts.Filter.Conditions = append(opts.Filter.Conditions, repository.FilterCondition{
		Field:    "category_id",
		Operator: repository.FilterOperatorEq,
		Value:    categoryID,
	})

	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type template list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list ticket type templates")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}
