package tickets

import (
	"context"
	"encoding/json"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
	"github.com/biairmal/guest-management-be/internal/features/events/workflowstep"
)

// emptyJSONObject is the default value stored for rules when the caller
// omits it, matching the ticket_types.rules column default of '{}'.
var emptyJSONObject = json.RawMessage("{}")

// TicketTypeListConfig declares the allow-listed sort/filter fields for
// ticket type list queries, enforced here in the service via
// query.ValidateListParams and reused by TicketTypeHandler.List for
// query.ParseListParams. event_id is always scoped from the URL, not a
// query filter.
var TicketTypeListConfig = query.ListParseConfig{
	AllowedSortFields:   []string{"id", "name", "created_at", "updated_at"},
	AllowedFilterFields: []string{"name"},
}

// TicketTypeService defines the application-level operations for
// event-scoped ticket types. Every operation takes the owning event's ID so
// a ticket type can never be read, changed, or deleted through a mismatched
// event in the URL.
//
// No //go:generate mock is declared for this interface: nothing in this
// codebase mocks a feature's own service (no handler-level tests exist yet —
// see docs/TESTING.md), and generating one into the same mocks/tickets
// package as TicketTypeWorkflowStepRepository's mock would create an import
// cycle back into this package from this package's own tests. Add one if a
// future consumer (e.g. a handler test) actually needs it.
type TicketTypeService interface {
	Create(ctx context.Context, eventID uuid.UUID, in CreateTicketTypeInput) (*TicketType, error)
	// GetByID returns a ticket type scoped to eventID with WorkflowStepIDs
	// populated (one extra lookup) — the only read operation that reports
	// workflow-step applicability.
	GetByID(ctx context.Context, eventID, id uuid.UUID) (*TicketType, error)
	Update(ctx context.Context, eventID, id uuid.UUID, in UpdateTicketTypeInput) (*TicketType, error)
	Delete(ctx context.Context, eventID, id uuid.UUID) error
	List(ctx context.Context, eventID uuid.UUID, params *query.ListParams) (*common.PageResponse[TicketType], error)
	// ReplaceWorkflowSteps replaces the full set of workflow steps id
	// applies to with workflowStepIDs (full-replace, no incremental
	// add/remove), rejecting any ID that doesn't belong to eventID.
	ReplaceWorkflowSteps(
		ctx context.Context, eventID, id uuid.UUID, workflowStepIDs []uuid.UUID,
	) (*TicketType, error)
}

// ticketTypeServiceImpl is the concrete implementation of TicketTypeService.
type ticketTypeServiceImpl struct {
	repo             repository.Repository[TicketType, uuid.UUID]
	junctionRepo     TicketTypeWorkflowStepRepository
	workflowStepRepo repository.ReadRepository[workflowstep.WorkflowStep, uuid.UUID]
	logger           logger.Logger
}

// NewTicketTypeService returns a TicketTypeService with the given
// dependencies. workflowStepRepo is a cross-feature repository-type
// dependency — never events/workflowstep's service — the same direction as
// staffing's eventRepo/userRepo/roleRepo dependencies. It is a
// ReadRepository, not the full Repository: this service only ever reads
// workflow steps owned by events/workflowstep, never writes to them.
func NewTicketTypeService(
	logger logger.Logger,
	repo repository.Repository[TicketType, uuid.UUID],
	junctionRepo TicketTypeWorkflowStepRepository,
	workflowStepRepo repository.ReadRepository[workflowstep.WorkflowStep, uuid.UUID],
) TicketTypeService {
	return &ticketTypeServiceImpl{
		repo: repo, junctionRepo: junctionRepo, workflowStepRepo: workflowStepRepo, logger: logger,
	}
}

// Create creates a new ticket type under eventID. ID is generated by the
// service; rules defaults to an empty JSON object when omitted. Audit fields
// (created_at, updated_at) are set by the AuditableRepository; the
// (event_id, name) uniqueness invariant is DB-enforced and surfaces as
// errorz.Conflict.
//
// Right after the row is inserted, the new ticket type's workflow-step
// applicability is seeded to ALL of eventID's current workflow steps (fail
// open, not fail closed — see seedDefaultWorkflowSteps). This is
// best-effort, same as EventService.Create's template-copy: a lookup/assign
// failure is logged but does not fail ticket type creation.
func (s *ticketTypeServiceImpl) Create(
	ctx context.Context, eventID uuid.UUID, in CreateTicketTypeInput,
) (*TicketType, error) {
	rules := in.Rules
	if len(rules) == 0 {
		rules = emptyJSONObject
	}

	entity := &TicketType{ID: uuid.New(), EventID: eventID, Name: in.Name, Rules: rules}
	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("ticket type already exists for this event")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid ticket type data")
		}
		s.logger.ErrorWithContext(ctx, "ticket type create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create ticket type")
	}

	entity.WorkflowStepIDs = s.seedDefaultWorkflowSteps(ctx, eventID, entity.ID)

	s.logger.InfoWithContext(ctx, "ticket type created", logger.F("id", entity.ID), logger.F("event_id", eventID))
	return entity, nil
}

// seedDefaultWorkflowSteps looks up eventID's current workflow steps and
// assigns every one of them to ticketTypeID via
// TicketTypeWorkflowStepRepository.SetWorkflowStepIDs — an organizer
// forgetting to configure a new ticket type should fail open (full standard
// admission), not fail closed (guests silently blocked at check-in). A
// lookup or assign failure is logged and returns nil (empty applicability)
// rather than failing Create; narrowing a type down is then a deliberate
// ReplaceWorkflowSteps call.
func (s *ticketTypeServiceImpl) seedDefaultWorkflowSteps(
	ctx context.Context, eventID, ticketTypeID uuid.UUID,
) []uuid.UUID {
	steps, _, err := s.workflowStepRepo.List(ctx, &repository.ListOptions{
		Filter: repository.Filter{Conditions: []repository.FilterCondition{
			{Field: "event_id", Operator: repository.FilterOperatorEq, Value: eventID},
		}},
		Pagination: repository.Pagination{Limit: query.DefaultMaxSize},
	})
	if err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type default workflow step lookup failed",
			logger.F("event_id", eventID), logger.F("ticket_type_id", ticketTypeID), logger.F("error", err))
		return nil
	}

	ids := make([]uuid.UUID, len(steps))
	for i, step := range steps {
		ids[i] = step.ID
	}

	if err := s.junctionRepo.SetWorkflowStepIDs(ctx, ticketTypeID, ids); err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type default workflow step assign failed",
			logger.F("event_id", eventID), logger.F("ticket_type_id", ticketTypeID), logger.F("error", err))
		return nil
	}
	return ids
}

// loadScoped loads a ticket type by id, scoped to eventID, without
// populating WorkflowStepIDs — the shared lookup behind GetByID/Update/
// Delete/ReplaceWorkflowSteps.
func (s *ticketTypeServiceImpl) loadScoped(ctx context.Context, eventID, id uuid.UUID) (*TicketType, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("ticket type not found")
		}
		s.logger.ErrorWithContext(ctx, "ticket type get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get ticket type")
	}
	if entity.EventID != eventID {
		return nil, errorz.NotFound().WithMessage("ticket type not found")
	}
	return entity, nil
}

// GetByID returns a ticket type by ID scoped to eventID, with
// WorkflowStepIDs populated from the ticket_type_workflow_steps junction.
// Returns errorz.NotFound if the ticket type doesn't exist, is
// soft-deleted, or belongs to a different event.
func (s *ticketTypeServiceImpl) GetByID(ctx context.Context, eventID, id uuid.UUID) (*TicketType, error) {
	entity, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}

	ids, err := s.junctionRepo.WorkflowStepIDsByTicketTypeID(ctx, id)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type workflow step ids lookup failed",
			logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get ticket type")
	}
	entity.WorkflowStepIDs = ids
	return entity, nil
}

// Update updates a ticket type scoped to eventID. Only non-nil/non-empty
// fields in UpdateTicketTypeInput are applied; WorkflowStepIDs is left
// unpopulated (see TicketType doc). The updated_at field is set by the
// AuditableRepository; the (event_id, name) uniqueness invariant is
// DB-enforced and surfaces as errorz.Conflict.
func (s *ticketTypeServiceImpl) Update(
	ctx context.Context, eventID, id uuid.UUID, in UpdateTicketTypeInput,
) (*TicketType, error) {
	entity, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}

	if in.Name != nil {
		entity.Name = *in.Name
	}
	if len(in.Rules) > 0 {
		entity.Rules = in.Rules
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("ticket type not found")
		}
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("ticket type already exists for this event")
		}
		s.logger.ErrorWithContext(ctx, "ticket type update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update ticket type")
	}

	s.logger.InfoWithContext(ctx, "ticket type updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a ticket type scoped to eventID. The
// AuditableRepository handles setting deleted_at and updated_at.
func (s *ticketTypeServiceImpl) Delete(ctx context.Context, eventID, id uuid.UUID) error {
	if _, err := s.loadScoped(ctx, eventID, id); err != nil {
		return err
	}
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("ticket type not found")
		}
		s.logger.ErrorWithContext(ctx, "ticket type delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete ticket type")
	}
	s.logger.InfoWithContext(ctx, "ticket type deleted", logger.F("id", id))
	return nil
}

// List returns the ticket types for eventID with filter, sort, and
// pagination from query.ListParams. The event_id scope is enforced
// server-side regardless of query filters. WorkflowStepIDs is left
// unpopulated on every item (see TicketType doc).
func (s *ticketTypeServiceImpl) List(
	ctx context.Context, eventID uuid.UUID, params *query.ListParams,
) (*common.PageResponse[TicketType], error) {
	if err := query.ValidateListParams(params, TicketTypeListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	opts := query.ToListOptions(params)
	opts.Filter.Conditions = append(opts.Filter.Conditions, repository.FilterCondition{
		Field:    "event_id",
		Operator: repository.FilterOperatorEq,
		Value:    eventID,
	})

	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list ticket types")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// ReplaceWorkflowSteps replaces id's entire set of applicable workflow
// steps with workflowStepIDs, scoped to eventID. Every ID is validated to
// belong to eventID before anything is written — a step ID belonging to a
// different event (or that doesn't exist) is rejected as errorz.BadRequest,
// consistent with the full-replace, no-transaction Sync design documented
// in docs/FEATURES.md#workflow-steps.
func (s *ticketTypeServiceImpl) ReplaceWorkflowSteps(
	ctx context.Context, eventID, id uuid.UUID, workflowStepIDs []uuid.UUID,
) (*TicketType, error) {
	entity, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}

	for _, stepID := range workflowStepIDs {
		if err := s.validateWorkflowStepBelongsToEvent(ctx, eventID, stepID); err != nil {
			return nil, err
		}
	}

	if err := s.junctionRepo.SetWorkflowStepIDs(ctx, id, workflowStepIDs); err != nil {
		s.logger.ErrorWithContext(ctx, "ticket type workflow step replace failed",
			logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to replace ticket type workflow steps")
	}

	entity.WorkflowStepIDs = workflowStepIDs
	s.logger.InfoWithContext(ctx, "ticket type workflow steps replaced",
		logger.F("id", id), logger.F("count", len(workflowStepIDs)))
	return entity, nil
}

// validateWorkflowStepBelongsToEvent returns errorz.BadRequest if stepID
// doesn't exist or belongs to a different event than eventID.
func (s *ticketTypeServiceImpl) validateWorkflowStepBelongsToEvent(
	ctx context.Context, eventID, stepID uuid.UUID,
) error {
	step, err := s.workflowStepRepo.GetByID(ctx, stepID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.BadRequest().WithMessage("workflow step " + stepID.String() + " not found")
		}
		s.logger.ErrorWithContext(ctx, "ticket type workflow step lookup failed",
			logger.F("workflow_step_id", stepID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to look up workflow step")
	}
	if step.EventID != eventID {
		return errorz.BadRequest().WithMessage("workflow step " + stepID.String() + " does not belong to this event")
	}
	return nil
}
