// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/tickets (interfaces: TicketTypeWorkflowStepRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/tickets/mock_ticket_type_workflow_step_repository.go -package=mocktickets github.com/biairmal/guest-management-be/internal/features/tickets TicketTypeWorkflowStepRepository
//

// Package mocktickets is a generated GoMock package.
package mocktickets

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketTypeWorkflowStepRepository is a mock of TicketTypeWorkflowStepRepository interface.
type MockTicketTypeWorkflowStepRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketTypeWorkflowStepRepositoryMockRecorder
	isgomock struct{}
}

// MockTicketTypeWorkflowStepRepositoryMockRecorder is the mock recorder for MockTicketTypeWorkflowStepRepository.
type MockTicketTypeWorkflowStepRepositoryMockRecorder struct {
	mock *MockTicketTypeWorkflowStepRepository
}

// NewMockTicketTypeWorkflowStepRepository creates a new mock instance.
func NewMockTicketTypeWorkflowStepRepository(ctrl *gomock.Controller) *MockTicketTypeWorkflowStepRepository {
	mock := &MockTicketTypeWorkflowStepRepository{ctrl: ctrl}
	mock.recorder = &MockTicketTypeWorkflowStepRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketTypeWorkflowStepRepository) EXPECT() *MockTicketTypeWorkflowStepRepositoryMockRecorder {
	return m.recorder
}

// SetWorkflowStepIDs mocks base method.
func (m *MockTicketTypeWorkflowStepRepository) SetWorkflowStepIDs(ctx context.Context, ticketTypeID uuid.UUID, workflowStepIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkflowStepIDs", ctx, ticketTypeID, workflowStepIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkflowStepIDs indicates an expected call of SetWorkflowStepIDs.
func (mr *MockTicketTypeWorkflowStepRepositoryMockRecorder) SetWorkflowStepIDs(ctx, ticketTypeID, workflowStepIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkflowStepIDs", reflect.TypeOf((*MockTicketTypeWorkflowStepRepository)(nil).SetWorkflowStepIDs), ctx, ticketTypeID, workflowStepIDs)
}

// WorkflowStepIDsByTicketTypeID mocks base method.
func (m *MockTicketTypeWorkflowStepRepository) WorkflowStepIDsByTicketTypeID(ctx context.Context, ticketTypeID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowStepIDsByTicketTypeID", ctx, ticketTypeID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkflowStepIDsByTicketTypeID indicates an expected call of WorkflowStepIDsByTicketTypeID.
func (mr *MockTicketTypeWorkflowStepRepositoryMockRecorder) WorkflowStepIDsByTicketTypeID(ctx, ticketTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowStepIDsByTicketTypeID", reflect.TypeOf((*MockTicketTypeWorkflowStepRepository)(nil).WorkflowStepIDsByTicketTypeID), ctx, ticketTypeID)
}
