// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/events/workflowstep (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/events/workflowstep/mock_service.go -package=mockworkflowstep github.com/biairmal/guest-management-be/internal/features/events/workflowstep Service
//

// Package mockworkflowstep is a generated GoMock package.
package mockworkflowstep

import (
	context "context"
	reflect "reflect"

	dto "github.com/biairmal/go-sdk/lib/common/dto"
	query "github.com/biairmal/guest-management-be/internal/core/query"
	workflowstep "github.com/biairmal/guest-management-be/internal/features/events/workflowstep"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, eventID uuid.UUID, in workflowstep.CreateWorkflowStepInput) (*workflowstep.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, in)
	ret0, _ := ret[0].(*workflowstep.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, eventID, in)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, eventID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, eventID, id)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, eventID, id uuid.UUID) (*workflowstep.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, eventID, id)
	ret0, _ := ret[0].(*workflowstep.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, eventID, id)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, eventID uuid.UUID, params *query.ListParams) (*dto.PageResponse[workflowstep.WorkflowStep], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, params)
	ret0, _ := ret[0].(*dto.PageResponse[workflowstep.WorkflowStep])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, eventID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, eventID, params)
}

// Sync mocks base method.
func (m *MockService) Sync(ctx context.Context, eventID uuid.UUID, in []workflowstep.SyncWorkflowStepInput) ([]*workflowstep.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, eventID, in)
	ret0, _ := ret[0].([]*workflowstep.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockServiceMockRecorder) Sync(ctx, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockService)(nil).Sync), ctx, eventID, in)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, eventID, id uuid.UUID, in workflowstep.UpdateWorkflowStepInput) (*workflowstep.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, eventID, id, in)
	ret0, _ := ret[0].(*workflowstep.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, eventID, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, eventID, id, in)
}
