// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/core/authz (interfaces: PermissionResolver)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/authz/mock_permission_resolver.go -package=mockauthz github.com/biairmal/guest-management-be/internal/core/authz PermissionResolver
//

// Package mockauthz is a generated GoMock package.
package mockauthz

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionResolver is a mock of PermissionResolver interface.
type MockPermissionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionResolverMockRecorder
	isgomock struct{}
}

// MockPermissionResolverMockRecorder is the mock recorder for MockPermissionResolver.
type MockPermissionResolverMockRecorder struct {
	mock *MockPermissionResolver
}

// NewMockPermissionResolver creates a new mock instance.
func NewMockPermissionResolver(ctrl *gomock.Controller) *MockPermissionResolver {
	mock := &MockPermissionResolver{ctrl: ctrl}
	mock.recorder = &MockPermissionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionResolver) EXPECT() *MockPermissionResolverMockRecorder {
	return m.recorder
}

// ResolvePermissions mocks base method.
func (m *MockPermissionResolver) ResolvePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePermissions", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePermissions indicates an expected call of ResolvePermissions.
func (mr *MockPermissionResolverMockRecorder) ResolvePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePermissions", reflect.TypeOf((*MockPermissionResolver)(nil).ResolvePermissions), ctx, roleID)
}
