// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/core/authz (interfaces: EventRoleResolver)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/authz/mock_event_role_resolver.go -package=mockauthz github.com/biairmal/guest-management-be/internal/core/authz EventRoleResolver
//

// Package mockauthz is a generated GoMock package.
package mockauthz

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRoleResolver is a mock of EventRoleResolver interface.
type MockEventRoleResolver struct {
	ctrl     *gomock.Controller
	recorder *MockEventRoleResolverMockRecorder
	isgomock struct{}
}

// MockEventRoleResolverMockRecorder is the mock recorder for MockEventRoleResolver.
type MockEventRoleResolverMockRecorder struct {
	mock *MockEventRoleResolver
}

// NewMockEventRoleResolver creates a new mock instance.
func NewMockEventRoleResolver(ctrl *gomock.Controller) *MockEventRoleResolver {
	mock := &MockEventRoleResolver{ctrl: ctrl}
	mock.recorder = &MockEventRoleResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRoleResolver) EXPECT() *MockEventRoleResolverMockRecorder {
	return m.recorder
}

// ResolveEventRoleID mocks base method.
func (m *MockEventRoleResolver) ResolveEventRoleID(ctx context.Context, eventID, userID uuid.UUID) (uuid.UUID, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEventRoleID", ctx, eventID, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveEventRoleID indicates an expected call of ResolveEventRoleID.
func (mr *MockEventRoleResolverMockRecorder) ResolveEventRoleID(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEventRoleID", reflect.TypeOf((*MockEventRoleResolver)(nil).ResolveEventRoleID), ctx, eventID, userID)
}
