package tenants

import (
	"context"
	"encoding/json"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../mocks/tenants/mock_service.go -package=mocktenants github.com/biairmal/guest-management-be/internal/features/tenants TenantService

// emptyJSONObject is the default value stored for settings/branding when the
// caller omits them, matching the migration's column default of '{}'.
var emptyJSONObject = json.RawMessage("{}")

// TenantService defines the application-level operations for tenants.
type TenantService interface {
	Create(ctx context.Context, in CreateInput) (*Tenant, error)
	GetByID(ctx context.Context, id uuid.UUID) (*Tenant, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*Tenant, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Tenant], error)
}

// tenantServiceImpl is the concrete implementation of TenantService.
type tenantServiceImpl struct {
	repo   repository.Repository[Tenant, uuid.UUID]
	logger logger.Logger
}

// NewTenantService returns a TenantService with the given dependencies.
func NewTenantService(logger logger.Logger, repo repository.Repository[Tenant, uuid.UUID]) TenantService {
	return &tenantServiceImpl{logger: logger, repo: repo}
}

// CreateInput is the input for creating a tenant.
//
// swagger:model TenantCreateInput
type CreateInput struct {
	Name     string          `json:"name"               validate:"required"`
	Type     *string         `json:"type,omitempty"`
	Settings json.RawMessage `json:"settings,omitempty"`
	Branding json.RawMessage `json:"branding,omitempty"`
}

// UpdateInput is the input for updating a tenant.
//
// swagger:model TenantUpdateInput
type UpdateInput struct {
	Name     *string         `json:"name,omitempty"     validate:"omitempty,min=1"`
	Type     *string         `json:"type,omitempty"`
	Settings json.RawMessage `json:"settings,omitempty"`
	Branding json.RawMessage `json:"branding,omitempty"`
}

// Create creates a new tenant. ID is generated by the service; settings and
// branding default to an empty JSON object when omitted. Audit fields
// (created_at, updated_at) are set by the AuditableRepository.
func (s *tenantServiceImpl) Create(ctx context.Context, in CreateInput) (*Tenant, error) {
	settings := in.Settings
	if len(settings) == 0 {
		settings = emptyJSONObject
	}
	branding := in.Branding
	if len(branding) == 0 {
		branding = emptyJSONObject
	}

	entity := &Tenant{
		ID:       uuid.New(),
		Name:     in.Name,
		Type:     in.Type,
		Settings: settings,
		Branding: branding,
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("tenant already exists")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid tenant data")
		}
		s.logger.ErrorWithContext(ctx, "tenant create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create tenant")
	}

	s.logger.InfoWithContext(ctx, "tenant created", logger.F("id", entity.ID))
	return entity, nil
}

// GetByID returns a tenant by ID, or errorz.NotFound if not found or soft-deleted.
func (s *tenantServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*Tenant, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("tenant not found")
		}
		s.logger.ErrorWithContext(ctx, "tenant get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get tenant")
	}
	return entity, nil
}

// Update updates a tenant. Only non-nil fields in UpdateInput are applied.
// The updated_at field is set by the AuditableRepository.
func (s *tenantServiceImpl) Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*Tenant, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("tenant not found")
		}
		s.logger.ErrorWithContext(ctx, "tenant get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get tenant")
	}

	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.Type != nil {
		entity.Type = in.Type
	}
	if len(in.Settings) > 0 {
		entity.Settings = in.Settings
	}
	if len(in.Branding) > 0 {
		entity.Branding = in.Branding
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("tenant not found")
		}
		s.logger.ErrorWithContext(ctx, "tenant update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update tenant")
	}

	s.logger.InfoWithContext(ctx, "tenant updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a tenant. The AuditableRepository handles setting
// deleted_at and updated_at.
func (s *tenantServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("tenant not found")
		}
		s.logger.ErrorWithContext(ctx, "tenant delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete tenant")
	}
	s.logger.InfoWithContext(ctx, "tenant deleted", logger.F("id", id))
	return nil
}

// List returns tenants with filter, sort, and pagination from query.ListParams.
func (s *tenantServiceImpl) List(ctx context.Context, params *query.ListParams) (*common.PageResponse[Tenant], error) {
	opts := listParamsToListOptions(params)
	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "tenant list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list tenants")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// listParamsToListOptions converts query.ListParams to repository.ListOptions.
func listParamsToListOptions(params *query.ListParams) *repository.ListOptions {
	if params == nil {
		return &repository.ListOptions{}
	}

	page, size := params.Page, params.Size
	if page < 1 {
		page = 1
	}
	if size < 1 {
		size = 20
	}
	if size > 100 {
		size = 100
	}
	offset := (page - 1) * size

	// Convert simple equality filters to repository filter conditions.
	var conditions []repository.FilterCondition
	for field, value := range params.Filters {
		conditions = append(conditions, repository.FilterCondition{
			Field:    field,
			Operator: repository.FilterOperatorEq,
			Value:    value,
		})
	}

	// Convert common.SortSpec to repository.Sort.
	var sorts []repository.Sort
	for _, s := range params.Sorts {
		dir := repository.SortAsc
		if s.Direction == common.SortDesc {
			dir = repository.SortDesc
		}
		sorts = append(sorts, repository.Sort{Field: s.Field, Direction: dir})
	}

	return &repository.ListOptions{
		Filter:     repository.Filter{Conditions: conditions},
		Pagination: repository.Pagination{Limit: size, Offset: offset},
		Sorts:      sorts,
	}
}
