// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/tickets/tickettypetemplate (interfaces: WorkflowStepRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/tickets/tickettypetemplate/mock_workflow_step_repository.go -package=mocktickettypetemplate github.com/biairmal/guest-management-be/internal/features/tickets/tickettypetemplate WorkflowStepRepository
//

// Package mocktickettypetemplate is a generated GoMock package.
package mocktickettypetemplate

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowStepRepository is a mock of WorkflowStepRepository interface.
type MockWorkflowStepRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowStepRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowStepRepositoryMockRecorder is the mock recorder for MockWorkflowStepRepository.
type MockWorkflowStepRepositoryMockRecorder struct {
	mock *MockWorkflowStepRepository
}

// NewMockWorkflowStepRepository creates a new mock instance.
func NewMockWorkflowStepRepository(ctrl *gomock.Controller) *MockWorkflowStepRepository {
	mock := &MockWorkflowStepRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowStepRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowStepRepository) EXPECT() *MockWorkflowStepRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockWorkflowStepRepository) Insert(ctx context.Context, ticketTypeTemplateID uuid.UUID, workflowStepTemplateIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, ticketTypeTemplateID, workflowStepTemplateIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockWorkflowStepRepositoryMockRecorder) Insert(ctx, ticketTypeTemplateID, workflowStepTemplateIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWorkflowStepRepository)(nil).Insert), ctx, ticketTypeTemplateID, workflowStepTemplateIDs)
}

// WorkflowStepTemplateIDs mocks base method.
func (m *MockWorkflowStepRepository) WorkflowStepTemplateIDs(ctx context.Context, ticketTypeTemplateIDs []uuid.UUID) (map[uuid.UUID][]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowStepTemplateIDs", ctx, ticketTypeTemplateIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkflowStepTemplateIDs indicates an expected call of WorkflowStepTemplateIDs.
func (mr *MockWorkflowStepRepositoryMockRecorder) WorkflowStepTemplateIDs(ctx, ticketTypeTemplateIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowStepTemplateIDs", reflect.TypeOf((*MockWorkflowStepRepository)(nil).WorkflowStepTemplateIDs), ctx, ticketTypeTemplateIDs)
}
