package users

import (
	"context"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"
	"golang.org/x/crypto/bcrypt"

	"github.com/biairmal/guest-management-be/internal/core/query"
	"github.com/biairmal/guest-management-be/internal/features/roles"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../mocks/users/mock_service.go -package=mockusers github.com/biairmal/guest-management-be/internal/features/users UserService

// UserService defines the application-level operations for users.
type UserService interface {
	Create(ctx context.Context, in CreateInput) (*User, error)
	GetByID(ctx context.Context, id uuid.UUID) (*User, error)
	// GetByEmail returns a user by email (unique across all tenants), or
	// errorz.NotFound if none exists. Used by the auth feature for login.
	GetByEmail(ctx context.Context, email string) (*User, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*User, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[User], error)
}

// userServiceImpl is the concrete implementation of UserService.
type userServiceImpl struct {
	repo     repository.Repository[User, uuid.UUID]
	roleRepo repository.Repository[roles.Role, uuid.UUID]
	logger   logger.Logger
}

// NewUserService returns a UserService with the given dependencies. roleRepo
// is used to validate that a user's role_id references a system-scope role
// (see docs/STAFFING_RBAC.md ss3) — a cross-feature repository-type
// dependency, not a service-to-service one, mirroring the auth->users
// precedent (see docs/ARCHITECTURE.md "Feature slice = future service boundary").
func NewUserService(
	logger logger.Logger, repo repository.Repository[User, uuid.UUID],
	roleRepo repository.Repository[roles.Role, uuid.UUID],
) UserService {
	return &userServiceImpl{logger: logger, repo: repo, roleRepo: roleRepo}
}

// validateSystemScopeRole loads roleID and returns errorz.NotFound if it
// doesn't exist, or errorz.BadRequest if it exists but isn't a system-scope
// role — a user's role_id must reference a role assignable to a tenant-wide
// role (see docs/STAFFING_RBAC.md ss3), never an event-scoped one.
func (s *userServiceImpl) validateSystemScopeRole(ctx context.Context, roleID uuid.UUID) error {
	role, err := s.roleRepo.GetByID(ctx, roleID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("role not found")
		}
		s.logger.ErrorWithContext(ctx, "user role lookup failed", logger.F("role_id", roleID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to look up role")
	}
	if role.Scope != roles.ScopeSystem {
		return errorz.BadRequest().WithMessage("role_id must reference a system-scope role")
	}
	return nil
}

// CreateInput is the input for creating a user. tenant_id is set once at
// creation and is not part of UpdateInput — users do not move tenants.
//
// swagger:model UserCreateInput
type CreateInput struct {
	TenantID       uuid.UUID `json:"tenant_id"                 validate:"required"`
	Email          string    `json:"email"                     validate:"required,email"`
	Password       string    `json:"password"                  validate:"required,min=8"`
	RoleID         uuid.UUID `json:"role_id"                   validate:"required"`
	IsTenantMaster bool      `json:"is_tenant_master,omitempty"`
}

// UpdateInput is the input for updating a user. Only non-nil fields are
// applied; a non-nil Password is re-hashed before storage.
//
// swagger:model UserUpdateInput
type UpdateInput struct {
	Email          *string    `json:"email,omitempty"    validate:"omitempty,email"`
	Password       *string    `json:"password,omitempty" validate:"omitempty,min=8"`
	RoleID         *uuid.UUID `json:"role_id,omitempty"`
	IsTenantMaster *bool      `json:"is_tenant_master,omitempty"`
}

// hashPassword returns the bcrypt hash of password, or an internal errorz on failure.
func hashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to hash password")
	}
	return string(hash), nil
}

// Create creates a new user. ID is generated by the service; the password is
// hashed before storage and never returned. Audit fields (created_at,
// updated_at) are set by the AuditableRepository.
func (s *userServiceImpl) Create(ctx context.Context, in CreateInput) (*User, error) {
	if err := s.validateSystemScopeRole(ctx, in.RoleID); err != nil {
		return nil, err
	}

	hash, err := hashPassword(in.Password)
	if err != nil {
		return nil, err
	}

	entity := &User{
		ID:             uuid.New(),
		TenantID:       in.TenantID,
		Email:          in.Email,
		PasswordHash:   hash,
		RoleID:         in.RoleID,
		IsTenantMaster: in.IsTenantMaster,
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("user already exists")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid user data")
		}
		s.logger.ErrorWithContext(ctx, "user create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create user")
	}

	s.logger.InfoWithContext(ctx, "user created", logger.F("id", entity.ID))
	return entity, nil
}

// GetByID returns a user by ID, or errorz.NotFound if not found or soft-deleted.
func (s *userServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*User, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("user not found")
		}
		s.logger.ErrorWithContext(ctx, "user get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get user")
	}
	return entity, nil
}

// GetByEmail returns a user by email, or errorz.NotFound if none exists.
// Email is unique across all tenants (migration 000012), so no tenant scope
// is needed to disambiguate.
func (s *userServiceImpl) GetByEmail(ctx context.Context, email string) (*User, error) {
	opts := &repository.ListOptions{
		Filter: repository.Filter{Conditions: []repository.FilterCondition{
			{Field: "email", Operator: repository.FilterOperatorEq, Value: email},
		}},
		Pagination: repository.Pagination{Limit: 1},
	}
	items, _, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "user get by email failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get user")
	}
	if len(items) == 0 {
		return nil, errorz.NotFound().WithMessage("user not found")
	}
	return items[0], nil
}

// applyUpdate mutates entity in place with every non-nil field of in,
// re-hashing a provided password and re-validating a provided role_id's
// scope. Split out of Update to keep that method's cognitive complexity
// within the lint budget.
func (s *userServiceImpl) applyUpdate(ctx context.Context, entity *User, in UpdateInput) error {
	if in.Email != nil {
		entity.Email = *in.Email
	}
	if in.Password != nil {
		hash, hashErr := hashPassword(*in.Password)
		if hashErr != nil {
			return hashErr
		}
		entity.PasswordHash = hash
	}
	if in.RoleID != nil {
		if err := s.validateSystemScopeRole(ctx, *in.RoleID); err != nil {
			return err
		}
		entity.RoleID = *in.RoleID
	}
	if in.IsTenantMaster != nil {
		entity.IsTenantMaster = *in.IsTenantMaster
	}
	return nil
}

// Update updates a user. Only non-nil fields in UpdateInput are applied; a
// non-nil Password is re-hashed. The updated_at field is set by the
// AuditableRepository.
func (s *userServiceImpl) Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*User, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("user not found")
		}
		s.logger.ErrorWithContext(ctx, "user get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get user")
	}

	if err := s.applyUpdate(ctx, entity, in); err != nil {
		return nil, err
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("user not found")
		}
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("user already exists")
		}
		s.logger.ErrorWithContext(ctx, "user update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update user")
	}

	s.logger.InfoWithContext(ctx, "user updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a user. The AuditableRepository handles setting
// deleted_at and updated_at.
func (s *userServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("user not found")
		}
		s.logger.ErrorWithContext(ctx, "user delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete user")
	}
	s.logger.InfoWithContext(ctx, "user deleted", logger.F("id", id))
	return nil
}

// List returns users with filter, sort, and pagination from query.ListParams.
func (s *userServiceImpl) List(ctx context.Context, params *query.ListParams) (*common.PageResponse[User], error) {
	opts := listParamsToListOptions(params)
	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "user list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list users")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// listParamsToListOptions converts query.ListParams to repository.ListOptions.
func listParamsToListOptions(params *query.ListParams) *repository.ListOptions {
	if params == nil {
		return &repository.ListOptions{}
	}

	page, size := params.Page, params.Size
	if page < 1 {
		page = 1
	}
	if size < 1 {
		size = 20
	}
	if size > 100 {
		size = 100
	}
	offset := (page - 1) * size

	// Convert simple equality filters to repository filter conditions.
	var conditions []repository.FilterCondition
	for field, value := range params.Filters {
		conditions = append(conditions, repository.FilterCondition{
			Field:    field,
			Operator: repository.FilterOperatorEq,
			Value:    value,
		})
	}

	// Convert common.SortSpec to repository.Sort.
	var sorts []repository.Sort
	for _, s := range params.Sorts {
		dir := repository.SortAsc
		if s.Direction == common.SortDesc {
			dir = repository.SortDesc
		}
		sorts = append(sorts, repository.Sort{Field: s.Field, Direction: dir})
	}

	return &repository.ListOptions{
		Filter:     repository.Filter{Conditions: conditions},
		Pagination: repository.Pagination{Limit: size, Offset: offset},
		Sorts:      sorts,
	}
}
