// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/events/category (interfaces: TemplateVersionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/events/category/mock_template_version_repository.go -package=mockcategory github.com/biairmal/guest-management-be/internal/features/events/category TemplateVersionRepository
//

// Package mockcategory is a generated GoMock package.
package mockcategory

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateVersionRepository is a mock of TemplateVersionRepository interface.
type MockTemplateVersionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateVersionRepositoryMockRecorder
	isgomock struct{}
}

// MockTemplateVersionRepositoryMockRecorder is the mock recorder for MockTemplateVersionRepository.
type MockTemplateVersionRepositoryMockRecorder struct {
	mock *MockTemplateVersionRepository
}

// NewMockTemplateVersionRepository creates a new mock instance.
func NewMockTemplateVersionRepository(ctrl *gomock.Controller) *MockTemplateVersionRepository {
	mock := &MockTemplateVersionRepository{ctrl: ctrl}
	mock.recorder = &MockTemplateVersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateVersionRepository) EXPECT() *MockTemplateVersionRepositoryMockRecorder {
	return m.recorder
}

// TemplateVersionForShare mocks base method.
func (m *MockTemplateVersionRepository) TemplateVersionForShare(ctx context.Context, id uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TemplateVersionForShare", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TemplateVersionForShare indicates an expected call of TemplateVersionForShare.
func (mr *MockTemplateVersionRepositoryMockRecorder) TemplateVersionForShare(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TemplateVersionForShare", reflect.TypeOf((*MockTemplateVersionRepository)(nil).TemplateVersionForShare), ctx, id)
}

// TemplateVersionForUpdate mocks base method.
func (m *MockTemplateVersionRepository) TemplateVersionForUpdate(ctx context.Context, id uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TemplateVersionForUpdate", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TemplateVersionForUpdate indicates an expected call of TemplateVersionForUpdate.
func (mr *MockTemplateVersionRepositoryMockRecorder) TemplateVersionForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TemplateVersionForUpdate", reflect.TypeOf((*MockTemplateVersionRepository)(nil).TemplateVersionForUpdate), ctx, id)
}
