// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/events (interfaces: WorkflowStepTemplateService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/events/mock_workflow_step_template_service.go -package=mockevents github.com/biairmal/guest-management-be/internal/features/events WorkflowStepTemplateService
//

// Package mockevents is a generated GoMock package.
package mockevents

import (
	context "context"
	reflect "reflect"

	dto "github.com/biairmal/go-sdk/lib/common/dto"
	query "github.com/biairmal/guest-management-be/internal/core/query"
	events "github.com/biairmal/guest-management-be/internal/features/events"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowStepTemplateService is a mock of WorkflowStepTemplateService interface.
type MockWorkflowStepTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowStepTemplateServiceMockRecorder
	isgomock struct{}
}

// MockWorkflowStepTemplateServiceMockRecorder is the mock recorder for MockWorkflowStepTemplateService.
type MockWorkflowStepTemplateServiceMockRecorder struct {
	mock *MockWorkflowStepTemplateService
}

// NewMockWorkflowStepTemplateService creates a new mock instance.
func NewMockWorkflowStepTemplateService(ctrl *gomock.Controller) *MockWorkflowStepTemplateService {
	mock := &MockWorkflowStepTemplateService{ctrl: ctrl}
	mock.recorder = &MockWorkflowStepTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowStepTemplateService) EXPECT() *MockWorkflowStepTemplateServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowStepTemplateService) Create(ctx context.Context, categoryID uuid.UUID, in events.CreateWorkflowStepTemplateInput) (*events.WorkflowStepTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, categoryID, in)
	ret0, _ := ret[0].(*events.WorkflowStepTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowStepTemplateServiceMockRecorder) Create(ctx, categoryID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowStepTemplateService)(nil).Create), ctx, categoryID, in)
}

// Delete mocks base method.
func (m *MockWorkflowStepTemplateService) Delete(ctx context.Context, categoryID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, categoryID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowStepTemplateServiceMockRecorder) Delete(ctx, categoryID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowStepTemplateService)(nil).Delete), ctx, categoryID, id)
}

// GetByID mocks base method.
func (m *MockWorkflowStepTemplateService) GetByID(ctx context.Context, categoryID, id uuid.UUID) (*events.WorkflowStepTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, categoryID, id)
	ret0, _ := ret[0].(*events.WorkflowStepTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkflowStepTemplateServiceMockRecorder) GetByID(ctx, categoryID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkflowStepTemplateService)(nil).GetByID), ctx, categoryID, id)
}

// List mocks base method.
func (m *MockWorkflowStepTemplateService) List(ctx context.Context, categoryID uuid.UUID, params *query.ListParams) (*dto.PageResponse[events.WorkflowStepTemplate], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, categoryID, params)
	ret0, _ := ret[0].(*dto.PageResponse[events.WorkflowStepTemplate])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowStepTemplateServiceMockRecorder) List(ctx, categoryID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowStepTemplateService)(nil).List), ctx, categoryID, params)
}

// Update mocks base method.
func (m *MockWorkflowStepTemplateService) Update(ctx context.Context, categoryID, id uuid.UUID, in events.UpdateWorkflowStepTemplateInput) (*events.WorkflowStepTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, categoryID, id, in)
	ret0, _ := ret[0].(*events.WorkflowStepTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowStepTemplateServiceMockRecorder) Update(ctx, categoryID, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowStepTemplateService)(nil).Update), ctx, categoryID, id, in)
}
