// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/events (interfaces: WorkflowStepService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/events/mock_workflow_step_service.go -package=mockevents github.com/biairmal/guest-management-be/internal/features/events WorkflowStepService
//

// Package mockevents is a generated GoMock package.
package mockevents

import (
	context "context"
	reflect "reflect"

	dto "github.com/biairmal/go-sdk/lib/common/dto"
	query "github.com/biairmal/guest-management-be/internal/core/query"
	events "github.com/biairmal/guest-management-be/internal/features/events"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkflowStepService is a mock of WorkflowStepService interface.
type MockWorkflowStepService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowStepServiceMockRecorder
	isgomock struct{}
}

// MockWorkflowStepServiceMockRecorder is the mock recorder for MockWorkflowStepService.
type MockWorkflowStepServiceMockRecorder struct {
	mock *MockWorkflowStepService
}

// NewMockWorkflowStepService creates a new mock instance.
func NewMockWorkflowStepService(ctrl *gomock.Controller) *MockWorkflowStepService {
	mock := &MockWorkflowStepService{ctrl: ctrl}
	mock.recorder = &MockWorkflowStepServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowStepService) EXPECT() *MockWorkflowStepServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowStepService) Create(ctx context.Context, eventID uuid.UUID, in events.CreateWorkflowStepInput) (*events.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, eventID, in)
	ret0, _ := ret[0].(*events.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowStepServiceMockRecorder) Create(ctx, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowStepService)(nil).Create), ctx, eventID, in)
}

// Delete mocks base method.
func (m *MockWorkflowStepService) Delete(ctx context.Context, eventID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowStepServiceMockRecorder) Delete(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowStepService)(nil).Delete), ctx, eventID, id)
}

// GetByID mocks base method.
func (m *MockWorkflowStepService) GetByID(ctx context.Context, eventID, id uuid.UUID) (*events.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, eventID, id)
	ret0, _ := ret[0].(*events.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkflowStepServiceMockRecorder) GetByID(ctx, eventID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkflowStepService)(nil).GetByID), ctx, eventID, id)
}

// List mocks base method.
func (m *MockWorkflowStepService) List(ctx context.Context, eventID uuid.UUID, params *query.ListParams) (*dto.PageResponse[events.WorkflowStep], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, eventID, params)
	ret0, _ := ret[0].(*dto.PageResponse[events.WorkflowStep])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWorkflowStepServiceMockRecorder) List(ctx, eventID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWorkflowStepService)(nil).List), ctx, eventID, params)
}

// Sync mocks base method.
func (m *MockWorkflowStepService) Sync(ctx context.Context, eventID uuid.UUID, in []events.SyncWorkflowStepInput) ([]*events.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, eventID, in)
	ret0, _ := ret[0].([]*events.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockWorkflowStepServiceMockRecorder) Sync(ctx, eventID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockWorkflowStepService)(nil).Sync), ctx, eventID, in)
}

// Update mocks base method.
func (m *MockWorkflowStepService) Update(ctx context.Context, eventID, id uuid.UUID, in events.UpdateWorkflowStepInput) (*events.WorkflowStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, eventID, id, in)
	ret0, _ := ret[0].(*events.WorkflowStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowStepServiceMockRecorder) Update(ctx, eventID, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowStepService)(nil).Update), ctx, eventID, id, in)
}
