package templates

import (
	"context"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../mocks/templates/mock_service.go -package=mocktemplates github.com/biairmal/guest-management-be/internal/features/templates MessageTemplateService

// MessageTemplateListConfig declares the allow-listed sort/filter fields for
// message template list queries, enforced here in the service via
// query.ValidateListParams and reused by MessageTemplateHandler.List for
// query.ParseListParams.
var MessageTemplateListConfig = query.ListParseConfig{
	AllowedSortFields: []string{
		"id", "source", "tenant_id", "event_id", "name", "channel", "created_at", "updated_at",
	},
	AllowedFilterFields: []string{"name", "source", "tenant_id", "event_id", "channel"},
}

// MessageTemplateService defines the application-level operations for message templates.
type MessageTemplateService interface {
	Create(ctx context.Context, in CreateInput) (*MessageTemplate, error)
	GetByID(ctx context.Context, id uuid.UUID) (*MessageTemplate, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*MessageTemplate, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[MessageTemplate], error)
}

// messageTemplateServiceImpl is the concrete implementation of MessageTemplateService.
type messageTemplateServiceImpl struct {
	repo   repository.Repository[MessageTemplate, uuid.UUID]
	logger logger.Logger
}

// NewMessageTemplateService returns a MessageTemplateService with the given dependencies.
func NewMessageTemplateService(
	logger logger.Logger, repo repository.Repository[MessageTemplate, uuid.UUID],
) MessageTemplateService {
	return &messageTemplateServiceImpl{logger: logger, repo: repo}
}

// Create creates a new message template. ID is generated by the service.
// Audit fields (created_at, updated_at) are set by the AuditableRepository.
//
//nolint:gocritic // DTO passed by value to match the by-value CreateInput convention across feature services
func (s *messageTemplateServiceImpl) Create(ctx context.Context, in CreateInput) (*MessageTemplate, error) {
	entity := &MessageTemplate{
		ID:        uuid.New(),
		Source:    in.Source,
		TenantID:  in.TenantID,
		EventID:   in.EventID,
		Name:      in.Name,
		Channel:   in.Channel,
		Subject:   in.Subject,
		Body:      in.Body,
		Variables: in.Variables,
	}
	if err := validateMessageTemplateInvariants(entity); err != nil {
		return nil, err
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("message template already exists for this scope, name, and channel")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid message template data")
		}
		s.logger.ErrorWithContext(ctx, "message template create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create message template")
	}

	s.logger.InfoWithContext(ctx, "message template created", logger.F("id", entity.ID))
	return entity, nil
}

// GetByID returns a message template by ID, or errorz.NotFound if not found or soft-deleted.
func (s *messageTemplateServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*MessageTemplate, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("message template not found")
		}
		s.logger.ErrorWithContext(ctx, "message template get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get message template")
	}
	return entity, nil
}

// Update updates a message template. Only non-nil fields in UpdateInput are
// applied; the source/channel invariants re-apply to the resulting record.
// The updated_at field is set by the AuditableRepository.
//
//nolint:gocritic // DTO passed by value to match the by-value UpdateInput convention across feature services
func (s *messageTemplateServiceImpl) Update(
	ctx context.Context, id uuid.UUID, in UpdateInput,
) (*MessageTemplate, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("message template not found")
		}
		s.logger.ErrorWithContext(ctx, "message template get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get message template")
	}

	applyMessageTemplateUpdate(entity, in)
	if err := validateMessageTemplateInvariants(entity); err != nil {
		return nil, err
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("message template not found")
		}
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("message template already exists for this scope, name, and channel")
		}
		s.logger.ErrorWithContext(ctx, "message template update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update message template")
	}

	s.logger.InfoWithContext(ctx, "message template updated", logger.F("id", id))
	return entity, nil
}

// applyMessageTemplateUpdate copies the non-nil fields of in onto entity.
//
//nolint:gocritic // DTO passed by value to match the by-value UpdateInput convention across feature services
func applyMessageTemplateUpdate(entity *MessageTemplate, in UpdateInput) {
	if in.Source != nil {
		entity.Source = *in.Source
	}
	if in.TenantID != nil {
		entity.TenantID = in.TenantID
	}
	if in.EventID != nil {
		entity.EventID = in.EventID
	}
	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.Channel != nil {
		entity.Channel = *in.Channel
	}
	if in.Subject != nil {
		entity.Subject = in.Subject
	}
	if in.Body != nil {
		entity.Body = *in.Body
	}
	if in.Variables != nil {
		entity.Variables = in.Variables
	}
}

// validateMessageTemplateInvariants enforces the cross-field business rules
// that a struct tag can't express: tenant_id/event_id must match source
// (mirroring the DB's chk_message_template_source constraint), and subject
// is required for email, forbidden for whatsapp.
func validateMessageTemplateInvariants(entity *MessageTemplate) error {
	if err := validateMessageTemplateScope(entity); err != nil {
		return err
	}
	return validateMessageTemplateSubject(entity)
}

// validateMessageTemplateScope enforces the source/tenant_id/event_id invariant.
func validateMessageTemplateScope(entity *MessageTemplate) error {
	switch entity.Source {
	case SourceApp:
		if entity.TenantID != nil || entity.EventID != nil {
			return errorz.BadRequest().WithMessage("tenant_id and event_id must be null when source is 'app'")
		}
	case SourceTenant:
		if entity.TenantID == nil {
			return errorz.BadRequest().WithMessage("tenant_id is required when source is 'tenant'")
		}
		if entity.EventID != nil {
			return errorz.BadRequest().WithMessage("event_id must be null when source is 'tenant'")
		}
	case SourceEvent:
		if entity.TenantID == nil || entity.EventID == nil {
			return errorz.BadRequest().WithMessage("tenant_id and event_id are required when source is 'event'")
		}
	}
	return nil
}

// validateMessageTemplateSubject enforces the channel/subject invariant.
func validateMessageTemplateSubject(entity *MessageTemplate) error {
	switch entity.Channel {
	case ChannelEmail:
		if entity.Subject == nil || *entity.Subject == "" {
			return errorz.BadRequest().WithMessage("subject is required when channel is 'email'")
		}
	case ChannelWhatsapp:
		if entity.Subject != nil && *entity.Subject != "" {
			return errorz.BadRequest().WithMessage("subject must be empty when channel is 'whatsapp'")
		}
	}
	return nil
}

// Delete soft-deletes a message template. The AuditableRepository handles
// setting deleted_at and updated_at.
func (s *messageTemplateServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("message template not found")
		}
		s.logger.ErrorWithContext(ctx, "message template delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete message template")
	}
	s.logger.InfoWithContext(ctx, "message template deleted", logger.F("id", id))
	return nil
}

// List returns message templates with filter, sort, and pagination from query.ListParams.
func (s *messageTemplateServiceImpl) List(
	ctx context.Context, params *query.ListParams,
) (*common.PageResponse[MessageTemplate], error) {
	if err := query.ValidateListParams(params, MessageTemplateListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	items, total, err := s.repo.List(ctx, query.ToListOptions(params))
	if err != nil {
		s.logger.ErrorWithContext(ctx, "message template list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list message templates")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}
