package category

import (
	"context"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../../mocks/events/category/mock_service.go -package=mockcategory github.com/biairmal/guest-management-be/internal/features/events/category Service

// Service defines the application-level operations for event categories.
type Service interface {
	Create(ctx context.Context, in CreateInput) (*EventCategory, error)
	GetByID(ctx context.Context, id uuid.UUID) (*EventCategory, error)
	Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*EventCategory, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params *query.ListParams) (*common.PageResponse[EventCategory], error)
}

// categoryServiceImpl is the concrete implementation of Service.
type categoryServiceImpl struct {
	repo   repository.Repository[EventCategory, uuid.UUID]
	logger logger.Logger
}

// NewService returns a Service with the given dependencies.
func NewService(
	logger logger.Logger,
	repo repository.Repository[EventCategory, uuid.UUID],
) Service {
	return &categoryServiceImpl{logger: logger, repo: repo}
}

// Create creates a new event category. ID is generated by the service.
// Audit fields (created_at, updated_at) are set by the AuditableRepository.
func (s *categoryServiceImpl) Create(ctx context.Context, in CreateInput) (*EventCategory, error) {
	if in.Source == SourceApp && in.TenantID != nil {
		return nil, errorz.BadRequest().WithMessage("tenant_id must be null when source is 'app'")
	}
	if in.Source == SourceTenant && in.TenantID == nil {
		return nil, errorz.BadRequest().WithMessage("tenant_id is required when source is 'tenant'")
	}

	entity := &EventCategory{
		ID:       uuid.New(),
		Source:   in.Source,
		TenantID: in.TenantID,
		Name:     in.Name,
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("event category already exists")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid event category data")
		}
		s.logger.ErrorWithContext(ctx, "event category create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create event category")
	}

	s.logger.InfoWithContext(ctx, "event category created", logger.F("id", entity.ID))
	return entity, nil
}

// GetByID returns an event category by ID, or errorz.NotFound if not found or soft-deleted.
func (s *categoryServiceImpl) GetByID(ctx context.Context, id uuid.UUID) (*EventCategory, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event category not found")
		}
		s.logger.ErrorWithContext(ctx, "event category get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event category")
	}
	return entity, nil
}

// Update updates an event category. Only non-nil fields in UpdateInput are applied.
// The updated_at field is set by the AuditableRepository.
func (s *categoryServiceImpl) Update(ctx context.Context, id uuid.UUID, in UpdateInput) (*EventCategory, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event category not found")
		}
		s.logger.ErrorWithContext(ctx, "event category get for update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get event category")
	}

	if in.Source != nil {
		entity.Source = *in.Source
	}
	if in.TenantID != nil {
		entity.TenantID = in.TenantID
	}
	if in.Name != nil {
		entity.Name = *in.Name
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("event category not found")
		}
		s.logger.ErrorWithContext(ctx, "event category update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update event category")
	}

	s.logger.InfoWithContext(ctx, "event category updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes an event category. The AuditableRepository handles
// setting deleted_at and updated_at.
func (s *categoryServiceImpl) Delete(ctx context.Context, id uuid.UUID) error {
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("event category not found")
		}
		s.logger.ErrorWithContext(ctx, "event category delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete event category")
	}
	s.logger.InfoWithContext(ctx, "event category deleted", logger.F("id", id))
	return nil
}

// EventCategoryListConfig declares the allow-listed sort/filter fields for
// event category list queries, enforced here in the service (the
// transport-agnostic authority) via query.ValidateListParams and reused by
// Handler.List for query.ParseListParams. Pagination (page/size/max
// size) is not set here, so it falls back to the shared defaults in
// internal/core/query.
var EventCategoryListConfig = query.ListParseConfig{
	AllowedSortFields:   []string{"id", "source", "tenant_id", "name", "created_at", "updated_at"},
	AllowedFilterFields: []string{"name", "source", "tenant_id"},
}

// List returns event categories with filter, sort, and pagination from query.ListParams.
func (s *categoryServiceImpl) List(
	ctx context.Context, params *query.ListParams,
) (*common.PageResponse[EventCategory], error) {
	if err := query.ValidateListParams(params, EventCategoryListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	items, total, err := s.repo.List(ctx, query.ToListOptions(params))
	if err != nil {
		s.logger.ErrorWithContext(ctx, "event category list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list event categories")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}
