package workflowsteptemplate

import (
	"context"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
)

//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -destination=../../../../mocks/events/workflowsteptemplate/mock_service.go -package=mockworkflowsteptemplate github.com/biairmal/guest-management-be/internal/features/events/workflowsteptemplate Service

// WorkflowStepTemplateListConfig declares the allow-listed sort/filter
// fields for workflow step template list queries, enforced here in the
// service via query.ValidateListParams and reused by
// Handler.List for query.ParseListParams. category_id is
// always scoped from the URL, not a query filter.
var WorkflowStepTemplateListConfig = query.ListParseConfig{
	AllowedSortFields:   []string{"id", "name", "order_index", "allows_multiple", "created_at", "updated_at"},
	AllowedFilterFields: []string{"name"},
}

// Service defines the application-level operations for
// category-scoped workflow step templates. Every operation takes the owning
// category's ID so a template can never be read, changed, or deleted through
// a mismatched category in the URL.
type Service interface {
	Create(
		ctx context.Context, categoryID uuid.UUID, in CreateWorkflowStepTemplateInput,
	) (*WorkflowStepTemplate, error)
	GetByID(ctx context.Context, categoryID, id uuid.UUID) (*WorkflowStepTemplate, error)
	Update(
		ctx context.Context, categoryID, id uuid.UUID, in UpdateWorkflowStepTemplateInput,
	) (*WorkflowStepTemplate, error)
	Delete(ctx context.Context, categoryID, id uuid.UUID) error
	List(
		ctx context.Context, categoryID uuid.UUID, params *query.ListParams,
	) (*common.PageResponse[WorkflowStepTemplate], error)
}

// workflowStepTemplateServiceImpl is the concrete implementation of Service.
type workflowStepTemplateServiceImpl struct {
	repo   repository.Repository[WorkflowStepTemplate, uuid.UUID]
	logger logger.Logger
}

// NewService returns a Service with the given dependencies.
func NewService(
	logger logger.Logger, repo repository.Repository[WorkflowStepTemplate, uuid.UUID],
) Service {
	return &workflowStepTemplateServiceImpl{logger: logger, repo: repo}
}

// Create creates a new workflow step template under categoryID. ID is
// generated by the service. Audit fields (created_at, updated_at) are set by
// the AuditableRepository; the (category_id, order_index) uniqueness
// invariant is DB-enforced and surfaces as errorz.Conflict.
func (s *workflowStepTemplateServiceImpl) Create(
	ctx context.Context, categoryID uuid.UUID, in CreateWorkflowStepTemplateInput,
) (*WorkflowStepTemplate, error) {
	entity := &WorkflowStepTemplate{
		ID:                      uuid.New(),
		CategoryID:              categoryID,
		Name:                    in.Name,
		OrderIndex:              in.OrderIndex,
		AllowsMultiple:          in.AllowsMultiple,
		TicketTypeApplicability: in.TicketTypeApplicability,
	}

	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("workflow step template already exists at this order index")
		}
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid workflow step template data")
		}
		s.logger.ErrorWithContext(ctx, "workflow step template create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create workflow step template")
	}

	s.logger.InfoWithContext(ctx, "workflow step template created",
		logger.F("id", entity.ID), logger.F("category_id", categoryID))
	return entity, nil
}

// GetByID returns a workflow step template by ID scoped to categoryID.
// Returns errorz.NotFound if the template doesn't exist, is soft-deleted, or
// belongs to a different category.
func (s *workflowStepTemplateServiceImpl) GetByID(
	ctx context.Context, categoryID, id uuid.UUID,
) (*WorkflowStepTemplate, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("workflow step template not found")
		}
		s.logger.ErrorWithContext(ctx, "workflow step template get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get workflow step template")
	}
	if entity.CategoryID != categoryID {
		return nil, errorz.NotFound().WithMessage("workflow step template not found")
	}
	return entity, nil
}

// Update updates a workflow step template scoped to categoryID. Only
// non-nil fields in UpdateWorkflowStepTemplateInput are applied. The
// updated_at field is set by the AuditableRepository.
func (s *workflowStepTemplateServiceImpl) Update(
	ctx context.Context, categoryID, id uuid.UUID, in UpdateWorkflowStepTemplateInput,
) (*WorkflowStepTemplate, error) {
	entity, err := s.GetByID(ctx, categoryID, id)
	if err != nil {
		return nil, err
	}

	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.OrderIndex != nil {
		entity.OrderIndex = *in.OrderIndex
	}
	if in.AllowsMultiple != nil {
		entity.AllowsMultiple = *in.AllowsMultiple
	}
	if in.TicketTypeApplicability != nil {
		entity.TicketTypeApplicability = in.TicketTypeApplicability
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("workflow step template not found")
		}
		if errors.Is(err, repository.ErrAlreadyExists) {
			return nil, errorz.Conflict().WithMessage("workflow step template already exists at this order index")
		}
		s.logger.ErrorWithContext(ctx, "workflow step template update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update workflow step template")
	}

	s.logger.InfoWithContext(ctx, "workflow step template updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a workflow step template scoped to categoryID. The
// AuditableRepository handles setting deleted_at and updated_at.
func (s *workflowStepTemplateServiceImpl) Delete(ctx context.Context, categoryID, id uuid.UUID) error {
	if _, err := s.GetByID(ctx, categoryID, id); err != nil {
		return err
	}
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("workflow step template not found")
		}
		s.logger.ErrorWithContext(ctx, "workflow step template delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete workflow step template")
	}
	s.logger.InfoWithContext(ctx, "workflow step template deleted", logger.F("id", id))
	return nil
}

// List returns the workflow step templates for categoryID with filter,
// sort, and pagination from query.ListParams. The category_id scope is
// enforced server-side regardless of query filters.
func (s *workflowStepTemplateServiceImpl) List(
	ctx context.Context, categoryID uuid.UUID, params *query.ListParams,
) (*common.PageResponse[WorkflowStepTemplate], error) {
	if err := query.ValidateListParams(params, WorkflowStepTemplateListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	opts := query.ToListOptions(params)
	opts.Filter.Conditions = append(opts.Filter.Conditions, repository.FilterCondition{
		Field:    "category_id",
		Operator: repository.FilterOperatorEq,
		Value:    categoryID,
	})

	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "workflow step template list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list workflow step templates")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}
