Logger:
  Level: debug # debug, info, warn, error, fatal, panic
  Output: stdout # stdout, stderr, file
  Format: text # json, text
  # ===== Rotation is only used if Output is file ===== #
  # Rotation:
  #   MaxSize: 100MB
  #   MaxAge: 7d
  #   MaxBackups: 3
  #   Compress: false
  #   LocalTime: false
  #   Filename: app.log

Server:
  Host: ${SERVER_HOST:127.0.0.1}
  Port: ${SERVER_PORT:8080}
  ReadHeaderTimeout: ${SERVER_READ_HEADER_TIMEOUT:5s}
  ReadTimeout: ${SERVER_READ_TIMEOUT:15s}
  WriteTimeout: ${SERVER_WRITE_TIMEOUT:15s}
  ShutdownTimeout: ${SERVER_SHUTDOWN_TIMEOUT:30s}

Database:
  Leader:
    Driver: postgres
    Host: ${DATABASE_HOST}
    Port: ${DATABASE_PORT}
    Database: ${DATABASE_DATABASE}
    Username: ${DATABASE_USERNAME}
    Password: ${DATABASE_PASSWORD}
    SSLMode: ${DATABASE_SSL_MODE:disable}
    ConnectTimeout: ${DATABASE_CONNECT_TIMEOUT:5s}
    MaxRetries: ${DATABASE_MAX_RETRIES:3}

Redis:
  Mode: standalone
  Address: ${REDIS_HOST:localhost}:${REDIS_PORT:6379}
  Username: ${REDIS_USERNAME:default}
  Password: ${REDIS_PASSWORD}
  DB: ${REDIS_DB:0}

Swagger:
  Enabled: ${SWAGGER_ENABLED:true}
  Username: ${SWAGGER_USERNAME}
  Password: ${SWAGGER_PASSWORD}
