// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/biairmal/guest-management-be/internal/features/guests (interfaces: PIIEncryptor)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/guests/mock_pii_encryptor.go -package=mockguests github.com/biairmal/guest-management-be/internal/features/guests PIIEncryptor
//

// Package mockguests is a generated GoMock package.
package mockguests

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPIIEncryptor is a mock of PIIEncryptor interface.
type MockPIIEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockPIIEncryptorMockRecorder
	isgomock struct{}
}

// MockPIIEncryptorMockRecorder is the mock recorder for MockPIIEncryptor.
type MockPIIEncryptorMockRecorder struct {
	mock *MockPIIEncryptor
}

// NewMockPIIEncryptor creates a new mock instance.
func NewMockPIIEncryptor(ctrl *gomock.Controller) *MockPIIEncryptor {
	mock := &MockPIIEncryptor{ctrl: ctrl}
	mock.recorder = &MockPIIEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPIIEncryptor) EXPECT() *MockPIIEncryptorMockRecorder {
	return m.recorder
}

// BlindIndex mocks base method.
func (m *MockPIIEncryptor) BlindIndex(value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlindIndex", value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlindIndex indicates an expected call of BlindIndex.
func (mr *MockPIIEncryptorMockRecorder) BlindIndex(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlindIndex", reflect.TypeOf((*MockPIIEncryptor)(nil).BlindIndex), value)
}

// Decrypt mocks base method.
func (m *MockPIIEncryptor) Decrypt(ciphertext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ciphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockPIIEncryptorMockRecorder) Decrypt(ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockPIIEncryptor)(nil).Decrypt), ciphertext)
}

// Encrypt mocks base method.
func (m *MockPIIEncryptor) Encrypt(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockPIIEncryptorMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockPIIEncryptor)(nil).Encrypt), plaintext)
}
