package guests

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"

	common "github.com/biairmal/go-sdk/lib/common/dto"
	"github.com/biairmal/go-sdk/lib/errorz"
	"github.com/biairmal/go-sdk/lib/logger"
	"github.com/biairmal/go-sdk/lib/repository"
	"github.com/google/uuid"

	"github.com/biairmal/guest-management-be/internal/core/query"
	"github.com/biairmal/guest-management-be/internal/features/events/event"
	"github.com/biairmal/guest-management-be/internal/features/tickets"
)

// No //go:generate mock is declared for this interface: nothing in this
// codebase mocks a feature's own service (no handler-level tests exist yet —
// see docs/TESTING.md), and generating one into the same mocks/guests
// package as PIIEncryptor's mock would create an import cycle back into this
// package from this package's own tests (same reasoning as
// tickets.TicketTypeService). Add one if a future consumer (e.g. a handler
// test) actually needs it.

// GuestListConfig declares the allow-listed sort/filter fields for guest list
// queries, enforced here in the service via query.ValidateListParams and
// reused by GuestHandler.List for query.ParseListParams. event_id is always
// scoped from the URL, not a query filter. email/phone only ever resolve to
// exact match (see rewriteEncryptedFilters) — a blind-index hash column has
// no notion of partial match.
var GuestListConfig = query.ListParseConfig{
	AllowedSortFields:   []string{"id", "name", "rsvp_status", "created_at", "updated_at"},
	AllowedFilterFields: []string{"name", "email", "phone", "rsvp_status"},
}

// GuestService defines the application-level operations for event-scoped
// guests. Every operation takes the owning event's ID so a guest can never be
// read, changed, or deleted through a mismatched event in the URL.
type GuestService interface {
	Create(ctx context.Context, eventID uuid.UUID, in CreateGuestInput) (*Guest, error)
	// GetByID returns a guest scoped to eventID with Ticket populated (one
	// extra lookup) once a ticket has been issued — the only read operation
	// that reports the QR/ticket summary.
	GetByID(ctx context.Context, eventID, id uuid.UUID) (*Guest, error)
	Update(ctx context.Context, eventID, id uuid.UUID, in UpdateGuestInput) (*Guest, error)
	Delete(ctx context.Context, eventID, id uuid.UUID) error
	List(ctx context.Context, eventID uuid.UUID, params *query.ListParams) (*common.PageResponse[Guest], error)
	// SendInvitation requires a ticket type already assigned; it generates an
	// invitation token and moves rsvp_status to invited. When the event's
	// rsvp_required is false, it also issues the guest's Ticket immediately.
	SendInvitation(ctx context.Context, eventID, id uuid.UUID) (*SendInvitationOutput, error)
	// RSVP looks a guest up by their invitation token (no event/auth
	// scoping — the token alone identifies the guest) and records status.
	// Confirming issues the guest's Ticket if one hasn't been issued yet.
	RSVP(ctx context.Context, token, status string) (*Guest, error)
}

// guestServiceImpl is the concrete implementation of GuestService.
type guestServiceImpl struct {
	repo           repository.Repository[Guest, uuid.UUID]
	ticketRepo     repository.Repository[Ticket, uuid.UUID]
	eventRepo      repository.ReadRepository[event.Event, uuid.UUID]
	ticketTypeRepo repository.ReadRepository[tickets.TicketType, uuid.UUID]
	encryptor      PIIEncryptor
	publisher      InvitationPublisher
	logger         logger.Logger
}

// NewGuestService returns a GuestService with the given dependencies.
// eventRepo/ticketTypeRepo are cross-feature repository-type dependencies —
// never another feature's service — the same direction as tickets'
// workflowStepRepo dependency. They are ReadRepository, not the full
// Repository: this service only ever calls GetByID on them. ticketRepo is a
// same-package (same-feature) dependency, so it's the full Repository —
// GuestService both creates and reads Ticket rows.
func NewGuestService(
	logger logger.Logger,
	repo repository.Repository[Guest, uuid.UUID],
	ticketRepo repository.Repository[Ticket, uuid.UUID],
	eventRepo repository.ReadRepository[event.Event, uuid.UUID],
	ticketTypeRepo repository.ReadRepository[tickets.TicketType, uuid.UUID],
	encryptor PIIEncryptor,
	publisher InvitationPublisher,
) GuestService {
	return &guestServiceImpl{
		repo: repo, ticketRepo: ticketRepo, eventRepo: eventRepo, ticketTypeRepo: ticketTypeRepo,
		encryptor: encryptor, publisher: publisher, logger: logger,
	}
}

// Create creates a new guest under eventID. ID is generated by the service;
// rsvp_status starts at RsvpStatusNone. A provided ticket_type_id is
// validated to belong to eventID. Audit fields (created_at, updated_at) are
// set by the audit repository decorator.
func (s *guestServiceImpl) Create(ctx context.Context, eventID uuid.UUID, in CreateGuestInput) (*Guest, error) {
	if in.TicketTypeID != nil {
		if err := s.validateTicketTypeBelongsToEvent(ctx, eventID, *in.TicketTypeID); err != nil {
			return nil, err
		}
	}

	entity := &Guest{
		ID: uuid.New(), EventID: eventID, Name: in.Name, Email: in.Email, Phone: in.Phone,
		TicketTypeID: in.TicketTypeID, RsvpStatus: RsvpStatusNone,
	}
	if err := s.repo.Create(ctx, entity); err != nil {
		if errors.Is(err, repository.ErrInvalidEntity) {
			return nil, errorz.UnprocessableEntity().WithMessage("invalid guest data")
		}
		s.logger.ErrorWithContext(ctx, "guest create failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to create guest")
	}

	s.logger.InfoWithContext(ctx, "guest created", logger.F("id", entity.ID), logger.F("event_id", eventID))
	return entity, nil
}

// validateTicketTypeBelongsToEvent returns errorz.BadRequest if ticketTypeID
// doesn't exist or belongs to a different event than eventID.
func (s *guestServiceImpl) validateTicketTypeBelongsToEvent(
	ctx context.Context, eventID, ticketTypeID uuid.UUID,
) error {
	tt, err := s.ticketTypeRepo.GetByID(ctx, ticketTypeID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.BadRequest().WithMessage("ticket type not found")
		}
		s.logger.ErrorWithContext(ctx, "guest ticket type lookup failed",
			logger.F("ticket_type_id", ticketTypeID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to look up ticket type")
	}
	if tt.EventID != eventID {
		return errorz.BadRequest().WithMessage("ticket type does not belong to this event")
	}
	return nil
}

// loadScoped loads a guest by id, scoped to eventID — the shared lookup
// behind GetByID/Update/Delete/SendInvitation.
func (s *guestServiceImpl) loadScoped(ctx context.Context, eventID, id uuid.UUID) (*Guest, error) {
	entity, err := s.repo.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("guest not found")
		}
		s.logger.ErrorWithContext(ctx, "guest get failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get guest")
	}
	if entity.EventID != eventID {
		return nil, errorz.NotFound().WithMessage("guest not found")
	}
	return entity, nil
}

// GetByID returns a guest by ID scoped to eventID, with Ticket populated once
// one has been issued.
func (s *guestServiceImpl) GetByID(ctx context.Context, eventID, id uuid.UUID) (*Guest, error) {
	entity, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}
	if entity.TicketID == nil {
		return entity, nil
	}
	ticket, err := s.ticketRepo.GetByID(ctx, *entity.TicketID)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest ticket lookup failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to get guest")
	}
	entity.Ticket = ticket
	return entity, nil
}

// Update updates a guest scoped to eventID. Only non-nil fields in
// UpdateGuestInput are applied; a provided ticket_type_id is re-validated to
// belong to eventID. The updated_at field is set by the audit repository
// decorator.
func (s *guestServiceImpl) Update(
	ctx context.Context, eventID, id uuid.UUID, in UpdateGuestInput,
) (*Guest, error) {
	entity, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}

	if in.Name != nil {
		entity.Name = *in.Name
	}
	if in.Email != nil {
		entity.Email = *in.Email
	}
	if in.Phone != nil {
		entity.Phone = in.Phone
	}
	if in.TicketTypeID != nil {
		if err := s.validateTicketTypeBelongsToEvent(ctx, eventID, *in.TicketTypeID); err != nil {
			return nil, err
		}
		entity.TicketTypeID = in.TicketTypeID
	}

	if err := s.repo.Update(ctx, id, entity); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, errorz.NotFound().WithMessage("guest not found")
		}
		s.logger.ErrorWithContext(ctx, "guest update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to update guest")
	}

	s.logger.InfoWithContext(ctx, "guest updated", logger.F("id", id))
	return entity, nil
}

// Delete soft-deletes a guest scoped to eventID. The audit repository
// decorator handles setting deleted_at and updated_at.
func (s *guestServiceImpl) Delete(ctx context.Context, eventID, id uuid.UUID) error {
	if _, err := s.loadScoped(ctx, eventID, id); err != nil {
		return err
	}
	if err := s.repo.Delete(ctx, id); err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return errorz.NotFound().WithMessage("guest not found")
		}
		s.logger.ErrorWithContext(ctx, "guest delete failed", logger.F("id", id), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to delete guest")
	}
	s.logger.InfoWithContext(ctx, "guest deleted", logger.F("id", id))
	return nil
}

// List returns the guests for eventID with filter, sort, and pagination from
// query.ListParams. The event_id scope is enforced server-side regardless of
// query filters.
func (s *guestServiceImpl) List(
	ctx context.Context, eventID uuid.UUID, params *query.ListParams,
) (*common.PageResponse[Guest], error) {
	if err := query.ValidateListParams(params, GuestListConfig); err != nil {
		return nil, errorz.BadRequest().WithMessage(err.Error())
	}
	if err := s.rewriteEncryptedFilters(ctx, params); err != nil {
		return nil, err
	}

	opts := query.ToListOptions(params)
	opts.Filter.Conditions = append(opts.Filter.Conditions, repository.FilterCondition{
		Field:    "event_id",
		Operator: repository.FilterOperatorEq,
		Value:    eventID,
	})

	items, total, err := s.repo.List(ctx, opts)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest list failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to list guests")
	}
	return common.NewPageResponse(items, total, params.Page, params.Size), nil
}

// rewriteEncryptedFilters replaces a present email/phone filter with its
// blind-index equivalent (email_hash/phone_hash), so query.ToListOptions
// (unaware of encryption) filters on the real column. Rejects (400) an
// email/phone filter whose resolved operator isn't eq — a blind-index hash
// column has no notion of partial match, so a caller-chosen "like" can never
// be honored honestly.
func (s *guestServiceImpl) rewriteEncryptedFilters(ctx context.Context, params *query.ListParams) error {
	for _, field := range [...]struct {
		name      string
		normalize func(string) string
	}{
		{"email", normalizeEmail},
		{"phone", normalizePhone},
	} {
		fv, ok := params.Filters[field.name]
		if !ok {
			continue
		}
		if fv.Operator != repository.FilterOperatorEq {
			return errorz.BadRequest().WithMessage(field.name + " only supports exact match")
		}
		hash, err := s.encryptor.BlindIndex(field.normalize(fv.Value))
		if err != nil {
			s.logger.ErrorWithContext(ctx, "guest filter blind index failed",
				logger.F("field", field.name), logger.F("error", err))
			return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to prepare " + field.name + " filter")
		}
		delete(params.Filters, field.name)
		params.Filters[field.name+"_hash"] = query.FilterValue{Value: hash, Operator: repository.FilterOperatorEq}
	}
	return nil
}

// SendInvitation requires eventID/id's guest to already have a ticket type
// assigned (400 otherwise). It generates a unique invitation token, moves
// rsvp_status to invited, and — when the event's rsvp_required is false —
// issues the guest's Ticket immediately (fail-closed on a lookup error: an
// event that can't be confirmed non-required is treated as requiring RSVP,
// so nothing is auto-issued). PublishInvitation is called best-effort: a
// failure is logged but does not fail this call, matching
// EventService.Create's template-copy precedent (FEATURES.md#events).
func (s *guestServiceImpl) SendInvitation(ctx context.Context, eventID, id uuid.UUID) (*SendInvitationOutput, error) {
	guest, err := s.loadScoped(ctx, eventID, id)
	if err != nil {
		return nil, err
	}
	if guest.TicketTypeID == nil {
		return nil, errorz.BadRequest().WithMessage("guest must have a ticket type assigned before an invitation can be sent")
	}

	token, err := generateToken(32)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest invitation token generation failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to generate invitation token")
	}
	guest.InvitationToken = &token
	guest.RsvpStatus = RsvpStatusInvited

	if !s.eventRequiresRSVP(ctx, eventID) {
		if err := s.issueTicketIfNeeded(ctx, guest); err != nil {
			return nil, err
		}
	}

	if err := s.repo.Update(ctx, id, guest); err != nil {
		s.logger.ErrorWithContext(ctx, "guest invitation update failed", logger.F("id", id), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to send invitation")
	}

	if err := s.publisher.PublishInvitation(ctx, InvitationMessage{
		GuestID: guest.ID.String(), EventID: eventID.String(), InvitationToken: token,
	}); err != nil {
		s.logger.ErrorWithContext(ctx, "guest invitation publish failed", logger.F("id", id), logger.F("error", err))
	}

	s.logger.InfoWithContext(ctx, "guest invitation sent", logger.F("id", id))
	return &SendInvitationOutput{Guest: guest, InvitationToken: token}, nil
}

// eventRequiresRSVP returns eventID's rsvp_required. A lookup failure is
// logged and treated as true (fail closed: don't auto-issue a ticket if we
// can't confirm the event doesn't require RSVP).
func (s *guestServiceImpl) eventRequiresRSVP(ctx context.Context, eventID uuid.UUID) bool {
	ev, err := s.eventRepo.GetByID(ctx, eventID)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest event rsvp_required lookup failed",
			logger.F("event_id", eventID), logger.F("error", err))
		return true
	}
	return ev.RsvpRequired
}

// RSVP looks up the guest owning token (404 if unknown) and records status.
// Confirming issues the guest's Ticket if one hasn't already been issued
// (idempotent — a no-op when the event's rsvp_required was false and
// SendInvitation already issued one). Declining leaves any already-issued
// ticket untouched, per product owner.
func (s *guestServiceImpl) RSVP(ctx context.Context, token, status string) (*Guest, error) {
	guest, err := s.findByInvitationToken(ctx, token)
	if err != nil {
		return nil, err
	}

	guest.RsvpStatus = status
	if status == RsvpStatusConfirmed {
		if err := s.issueTicketIfNeeded(ctx, guest); err != nil {
			return nil, err
		}
	}

	if err := s.repo.Update(ctx, guest.ID, guest); err != nil {
		s.logger.ErrorWithContext(ctx, "guest rsvp update failed", logger.F("id", guest.ID), logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to record rsvp")
	}

	s.logger.InfoWithContext(ctx, "guest rsvp recorded", logger.F("id", guest.ID), logger.F("status", status))
	return guest, nil
}

// findByInvitationToken looks up the one guest owning token. Not
// event-scoped — the token alone identifies the guest, since the caller is
// an unauthenticated guest with no event context of their own.
func (s *guestServiceImpl) findByInvitationToken(ctx context.Context, token string) (*Guest, error) {
	items, _, err := s.repo.List(ctx, &repository.ListOptions{
		Filter: repository.Filter{Conditions: []repository.FilterCondition{
			{Field: "invitation_token", Operator: repository.FilterOperatorEq, Value: token},
		}},
		Pagination: repository.Pagination{Limit: 1},
		SkipCount:  true,
	})
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest rsvp token lookup failed", logger.F("error", err))
		return nil, errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to look up invitation")
	}
	if len(items) == 0 {
		return nil, errorz.NotFound().WithMessage("invitation not found")
	}
	return items[0], nil
}

// issueTicketIfNeeded creates guest's Ticket and sets guest.TicketID/Ticket
// in memory (the caller persists guest via a single repo.Update). A no-op
// when guest.TicketID is already set.
func (s *guestServiceImpl) issueTicketIfNeeded(ctx context.Context, guest *Guest) error {
	if guest.TicketID != nil {
		return nil
	}
	if guest.TicketTypeID == nil {
		return errorz.BadRequest().WithMessage("guest has no ticket type assigned")
	}

	qrCode, err := generateToken(24)
	if err != nil {
		s.logger.ErrorWithContext(ctx, "guest ticket qr code generation failed",
			logger.F("guest_id", guest.ID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to generate ticket")
	}

	ticket := &Ticket{
		ID: uuid.New(), GuestID: guest.ID, EventID: guest.EventID, TicketTypeID: *guest.TicketTypeID,
		QRCode: qrCode, Status: TicketStatusActive,
	}
	if err := s.ticketRepo.Create(ctx, ticket); err != nil {
		s.logger.ErrorWithContext(ctx, "guest ticket create failed", logger.F("guest_id", guest.ID), logger.F("error", err))
		return errorz.Wrap(err).WithCode(errorz.CodeInternal).WithMessage("failed to issue ticket")
	}

	guest.TicketID = &ticket.ID
	guest.Ticket = ticket
	return nil
}

// generateToken returns a random URL-safe token of n random bytes, used for
// both invitation tokens and QR codes — an opaque, unguessable string, not a
// PII value, so it needs no encryption of its own.
func generateToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
