# mocks.mk - Generate gomock mocks for app-defined interfaces
#
# Provides: mocks, help-mocks. Prerequisite: include vars.mk first.
# Mocks are generated by the //go:generate directives next to each app-defined
# interface (e.g. events.CategoryService) into ./mocks, an ordinary package
# tree of this same module (go.uber.org/mock is a normal dependency of the
# main go.mod — harmless, since _test.go files never ship in the compiled
# binary). go-sdk interfaces (repository.Repository, logger.Logger, ...) are
# mocked by go-sdk itself; consume its ../go-sdk/mocks module instead of
# regenerating them here. Regenerate after changing any mocked interface.

include $(SCRIPTS_DIR)/vars.mk

# Packages that carry //go:generate mockgen directives.
MOCK_PKGS := ./internal/features/events/... ./internal/features/tenants/... ./internal/features/users/... ./internal/features/auth/... ./internal/features/templates/... ./internal/features/roles/... ./internal/features/staffing/... ./internal/core/validation/... ./internal/core/authz/...

mocks: ## Regenerate app-interface mocks into ./mocks (go.uber.org/mock)
	$(ECHO_EMPTY)
	@echo "# Mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_RUN)Generating mocks..."
	@go generate $(MOCK_PKGS)
	@echo "$(INDENT)$(PREFIX_OK)Mocks generated into ./mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_OK)PROCESS COMPLETED SUCCESSFULLY"

help-mocks: ## Show mock targets and descriptions
	@echo "# Mocks"
	@echo "  make mocks ## Regenerate app-interface mocks into ./mocks"
