# mocks.mk - Generate gomock mocks for app-defined interfaces
#
# Provides: mocks, help-mocks. Prerequisite: include vars.mk first.
# Mocks are generated by the //go:generate directives next to each app-defined
# interface (e.g. events.CategoryService) into the nested module ./mocks,
# which has its own go.mod so go.uber.org/mock never becomes a dependency of
# the main module. go-sdk interfaces (repository.Repository, logger.Logger,
# ...) are mocked by go-sdk itself; consume its ../go-sdk/mocks module instead
# of regenerating them here. Regenerate after changing any mocked interface.

include $(SCRIPTS_DIR)/vars.mk

# Packages that carry //go:generate mockgen directives.
MOCK_PKGS := ./internal/features/events/... ./internal/core/validation/...

mocks: ## Regenerate app-interface mocks into the ./mocks module (go.uber.org/mock)
	$(ECHO_EMPTY)
	@echo "# Mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_RUN)Generating mocks..."
	@go generate $(MOCK_PKGS)
	@echo "$(INDENT)$(PREFIX_RUN)Tidying mocks module..."
	@cd mocks && go mod tidy
	@echo "$(INDENT)$(PREFIX_OK)Mocks generated into ./mocks"
	$(ECHO_EMPTY)
	@echo "$(INDENT)$(PREFIX_OK)PROCESS COMPLETED SUCCESSFULLY"

help-mocks: ## Show mock targets and descriptions
	@echo "# Mocks"
	@echo "  make mocks ## Regenerate app-interface mocks into the ./mocks module"
